## LLAMA2 FINE TUNING WITH INSTACART DATA

**INSURANCE DATA TRAINING**

In [ ]:
!pip install -q -U trl transformers accelerate git+https://github.com/huggingface/peft.git
!pip install -q datasets bitsandbytes einops wandb

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.0/118.0 kB 3.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 37.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 251.2/251.2 kB 27.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 519.6/519.6 kB 40.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.8/294.8 kB 32.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 93.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 75.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 14.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 20.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 15.6 MB/s eta 0:00:00
  Building wheel for peft (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.6/92.6 MB 9.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 kB 5.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 85.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.8/188.8 kB 20.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 218.8/218.8 kB 24.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 6.7 MB/s eta 0:00:00
  Building wheel for pathtools (setup.py) ... done

In [ ]:
import pandas as pd
df_joined = pd.read_csv("/content/insurance_training_data_30k.csv")

In [ ]:
df_joined['text'] = df_joined.apply(lambda row: row['input_text'] + " ->: " + row['output_text'], axis = 1)

In [ ]:
from sklearn.model_selection import train_test_split
train_df, test_df = train_test_split(df_joined, test_size=0.2, random_state=42)

In [ ]:
train_df.head(10)

,input_text,output_text,text
24290,Act as an Insurance underwriting expert for AB...,Coverage Details:\n- Policy Name: Comprehensiv...,Act as an Insurance underwriting expert for AB...
19699,Act as an Insurance underwriting expert for AB...,Coverage Details:\n- Premium: $500 per month\n...,Act as an Insurance underwriting expert for AB...
15164,Act as an Insurance underwriting expert for AB...,Coverage Details:\nType of Health Insurance: C...,Act as an Insurance underwriting expert for AB...
13589,Act as an Insurance underwriting expert for AB...,Coverage Details:\nCoverage Type: Comprehensiv...,Act as an Insurance underwriting expert for AB...
25969,Act as an Insurance underwriting expert for AB...,Coverage Details:\nCoverage Level: Silver Plan...,Act as an Insurance underwriting expert for AB...
380,Act as an Insurance underwriting expert for AB...,Coverage Details:\n\nCoverage Areas:\nCoverage...,Act as an Insurance underwriting expert for AB...
32231,Act as an Insurance underwriting expert for AB...,Coverage Details:\n\nCoverage Areas:\n- Hospit...,Act as an Insurance underwriting expert for AB...
12051,Act as an Insurance underwriting expert for AB...,Coverage Details:\nType of Insurance: Health I...,Act as an Insurance underwriting expert for AB...
649,Act as an Insurance underwriting expert for AB...,Coverage Details:\nCoverage Type: Comprehensiv...,Act as an Insurance underwriting expert for AB...
14975,Act as an Insurance underwriting expert for AB...,Coverage Details:\n- Coverage Plan: Comprehens...,Act as an Insurance underwriting expert for AB...

In [ ]:
test_df.head(10)

,input_text,output_text,text
31330,Act as an Insurance underwriting expert for AB...,"Coverage Details:\n- Coverage Limit: $500,000 ...",Act as an Insurance underwriting expert for AB...
2848,Act as an Insurance underwriting expert for AB...,Coverage Details:\nCoverage Type: Health Insur...,Act as an Insurance underwriting expert for AB...
28069,Act as an Insurance underwriting expert for AB...,Coverage Details:**\n- Preferred Provider Orga...,Act as an Insurance underwriting expert for AB...
30623,Act as an Insurance underwriting expert for AB...,Coverage Details:\n- Premium Payment: Monthly\...,Act as an Insurance underwriting expert for AB...
18692,Act as an Insurance underwriting expert for AB...,Coverage Details:\nPremium Amount: $500 per mo...,Act as an Insurance underwriting expert for AB...
28349,Act as an Insurance underwriting expert for AB...,Coverage Details:\nPolicy Term: 1 year\nMonthl...,Act as an Insurance underwriting expert for AB...
20485,Act as an Insurance underwriting expert for AB...,Coverage Details:\nType of Coverage: Comprehen...,Act as an Insurance underwriting expert for AB...
10388,Act as an Insurance underwriting expert for AB...,Coverage Details:\nPremium Amount: $500 per mo...,Act as an Insurance underwriting expert for AB...
3833,Act as an Insurance underwriting expert for AB...,Coverage Details:\nType of Coverage: Health In...,Act as an Insurance underwriting expert for AB...
32083,Act as an Insurance underwriting expert for AB...,Coverage Details:\nCoverage Type: Comprehensiv...,Act as an Insurance underwriting expert for AB...

In [ ]:
from datasets import Dataset,DatasetDict
train_dataset_dict = DatasetDict({
    "train": Dataset.from_pandas(train_df),
})

In [ ]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, AutoTokenizer

model_name = "TinyPixel/Llama-2-7B-bf16-sharded"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    trust_remote_code=True
)
model.config.use_cache = False

Downloading (…)lve/main/config.json:   0%|          | 0.00/626 [00:00<?, ?B/s]

Downloading (…)model.bin.index.json:   0%|          | 0.00/26.8k [00:00<?, ?B/s]

Downloading shards:   0%|          | 0/14 [00:00<?, ?it/s]

Downloading (…)l-00001-of-00014.bin:   0%|          | 0.00/981M [00:00<?, ?B/s]

Downloading (…)l-00002-of-00014.bin:   0%|          | 0.00/967M [00:00<?, ?B/s]

Downloading (…)l-00003-of-00014.bin:   0%|          | 0.00/967M [00:00<?, ?B/s]

Downloading (…)l-00004-of-00014.bin:   0%|          | 0.00/990M [00:00<?, ?B/s]

Downloading (…)l-00005-of-00014.bin:   0%|          | 0.00/944M [00:00<?, ?B/s]

Downloading (…)l-00006-of-00014.bin:   0%|          | 0.00/990M [00:00<?, ?B/s]

Downloading (…)l-00007-of-00014.bin:   0%|          | 0.00/967M [00:00<?, ?B/s]

Downloading (…)l-00008-of-00014.bin:   0%|          | 0.00/967M [00:00<?, ?B/s]

Downloading (…)l-00009-of-00014.bin:   0%|          | 0.00/990M [00:00<?, ?B/s]

Downloading (…)l-00010-of-00014.bin:   0%|          | 0.00/944M [00:00<?, ?B/s]

Downloading (…)l-00011-of-00014.bin:   0%|          | 0.00/990M [00:00<?, ?B/s]

Downloading (…)l-00012-of-00014.bin:   0%|          | 0.00/967M [00:00<?, ?B/s]

Downloading (…)l-00013-of-00014.bin:   0%|          | 0.00/967M [00:00<?, ?B/s]

Downloading (…)l-00014-of-00014.bin:   0%|          | 0.00/847M [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/14 [00:00<?, ?it/s]

Downloading (…)neration_config.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token

Downloading (…)okenizer_config.json:   0%|          | 0.00/676 [00:00<?, ?B/s]

Downloading tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

Downloading (…)/main/tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

Downloading (…)cial_tokens_map.json:   0%|          | 0.00/411 [00:00<?, ?B/s]

In [ ]:
import transformers

pipeline = transformers.pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    # torch_dtype=torch.bfloat16,
    torch_dtype=torch.float16,
    trust_remote_code=True,
    device_map="auto",
)

In [ ]:
## BEFORE FINETUNING
test_data = ["""Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Name: Ayesha Nomani
Date of Birth: November 28, 1990
Gender: Female
Address: 123, Sarjapura Road, Bengaluru
Phone Number: +91 987654321
Email: nomani.ayesha@gmail.com
Occupation: Elementary School Teacher

Dependents:
1. Name: Firoz Nomani
Date of Birth: February 22, 1990
Gender: Male
Relationship: Husband

2. Name: Saya Nomani
Date of Birth: June 12, 2019
Relationship: Child

Medical History:
Primary Care Physician: Dr. Jyoti Awasthi
Last Medical Checkup Date: May 11, 2023
Medical Conditions: None

Allergies:
Allergy: Penicillin
Severity: Moderate

Medications:
Medication Name: None
Dosage: N/A
Frequency: N/A

Hospitalizations:
Hospital Name: Springfield Medical Center
Reason: Leg Surgery
Date: June 15, 2015 ->:
"""]

sequences = pipeline(
    test_data,
    max_length=512,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1417: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation )
  warnings.warn(

0 Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Name: Ayesha Nomani
Date of Birth: November 28, 1990
Gender: Female
Address: 123, Sarjapura Road, Bengaluru
Phone Number: +91 987654321
Email: nomani.ayesha@gmail.com
Occupation: Elementary School Teacher

Dependents:
1. Name: Firoz Nomani
Date of Birth: February 22, 1990
Gender: Male
Relationship: Husband

2. Name: Saya Nomani
Date of Birth: June 12, 2019
Relationship: Child

Medical History:
Primary Care Physician: Dr. Jyoti Awasthi
Last Medical Checkup Date: May 11, 2023
Medical Conditions: None

Allergies:
Allergy: Penicillin
Severity: Moderate

Medications:
Medication Name: None
Dosage: N/A
Frequency: N/A

Hospitalizations:
Hospital Name: Springfield Medical Center
Reason: Leg Surgery
Date: June 15, 2015 ->:

Hospitalization Details:
- Date: June 15, 2015
- Reason: Leg Surgery
- Hospital Name: Springfield Medical Center
- Doctor: Dr. Jyoti Awasthi

In the hospital, they gave the following medicines:
Name: Penicillin
Dose: 800mg
Type: Antibacterial
Date: July 1, 2015

Name: Paracetamol
Dose: 500mg
Type: Analgesic
Date: July 1, 2015

Name: Codeine
Dose: 8mg
Type: Anti-inflammatory
Date: July 1, 2015

Name: Diclofenac

In [ ]:
## BEFORE FINETUNING
test_data = ["""Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Jason Pitt
Date of Birth: May 25, 1981
Gender: Male
Address: 753, Richmond Street, California, USA
Phone Number: (555) 682920
Email: jason.pitt218@email.com
Occupation: Software Engineer

Dependents:
1. Name: Emma Pitt
Date of Birth: January 22, 1982
Gender: Female
Relationship: Wife
Dependent Type: Adult

2. Name: Emily Pitt
Date of Birth: June 12, 2005
Relationship: Child
Gender: Female

Medical History:
Primary Care Physician: Dr. Lisa Johnson

Last Medical Checkup Date: May 15, 2023

Medical Conditions: None

Allergies: None

Medications:

Medication Name: None
Dosage: N/A
Frequency: N/A
Hospitalizations:

Hospital Name: Anytown General Hospital
Reason: Appendectomy
Date: March 5, 2019
Surgeries:

Surgery Type: None ->:
"""]

sequences = pipeline(
    test_data,
    max_length=512,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

0 Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Jason Pitt
Date of Birth: May 25, 1981
Gender: Male
Address: 753, Richmond Street, California, USA
Phone Number: (555) 682920
Email: jason.pitt218@email.com
Occupation: Software Engineer

Dependents:
1. Name: Emma Pitt
Date of Birth: January 22, 1982
Gender: Female
Relationship: Wife
Dependent Type: Adult

2. Name: Emily Pitt
Date of Birth: June 12, 2005
Relationship: Child
Gender: Female

Medical History:
Primary Care Physician: Dr. Lisa Johnson

Last Medical Checkup Date: May 15, 2023

Medical Conditions: None

Allergies: None

Medications:

Medication Name: None
Dosage: N/A
Frequency: N/A
Hospitalizations:

Hospital Name: Anytown General Hospital
Reason: Appendectomy
Date: March 5, 2019
Surgeries:

Surgery Type: None ->:
Hospital: None
Reason: None
Date: April 13, 2022

Immunizations:

Vaccine Name: Covid-19
Dose: 1
Date: January 31, 2021
Provider Name: Dr. Johnson

Vaccine Name: None
Dose: 1
Date: July 25, 2018
Provider Name: Doctor John

Vaccine Name: None
Dose: 1
Date: January 29, 2017
Provider Name: Dr. Smith

Pre-existing Conditions:

Pre-existing Condition Type: None
Reason: None

Diagnosis:

Diagnosis Type: None

Doctors:

Doctor Name: None
Specialty

In [ ]:
## BEFORE FINETUNING
test_data = ["""Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Robert Johnson
Date of Birth: September 5, 1976
Gender: Male
Address: 789 Maple Lane, Riverside, NY
Phone Number: (555) 987-6543
Email: robert.johnson@email.com
Occupation: Accountant

Dependents:

1. Full Name: Olivia Johnson
Date of Birth: December 3, 2005
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Michael Davis
Last Medical Checkup Date: August 12, 2023
Medical Conditions: High Blood Pressure
Allergies: None
Medications:
Medication Name: Lisinopril
Dosage: 10 mg daily
Frequency: Daily
Hospitalizations:

Hospital Name: Riverside General Hospital
Reason: Kidney Stone
Date: July 15, 2010
Surgeries:

Surgery Type: Appendectomy ->:
"""]

sequences = pipeline(
    test_data,
    max_length=512,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

0 Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Robert Johnson
Date of Birth: September 5, 1976
Gender: Male
Address: 789 Maple Lane, Riverside, NY
Phone Number: (555) 987-6543
Email: robert.johnson@email.com
Occupation: Accountant

Dependents:

1. Full Name: Olivia Johnson
Date of Birth: December 3, 2005
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Michael Davis
Last Medical Checkup Date: August 12, 2023
Medical Conditions: High Blood Pressure
Allergies: None
Medications:
Medication Name: Lisinopril
Dosage: 10 mg daily
Frequency: Daily
Hospitalizations:

Hospital Name: Riverside General Hospital
Reason: Kidney Stone
Date: July 15, 2010
Surgeries:

Surgery Type: Appendectomy ->:
Surgery Name: Appending
Surgeon Name: Dr. James Johnson
Date: May 22, 2010
Procedures:

Procedure Type: Colonoscopy ->:
Procedure Name: Colonoscopy
Date: August 1, 2007
Procedures:

Procedure Type: Biopsy ->:
Procedure Name: Biopsy
Date: March 3, 2008
Procedures:

Procedure Type: MRI Scan ->:
Procedure Name: MRI Scan
Date: August 15, 2005
Procedures:

Procedure Type: Ultrasound ->:
Procedure Name: Ultrasound
Date: August 3, 2006
Procedures:

Procedure Type: Mammography ->:
Procedure Name: Mammography
Date: November 24, 2010

In [ ]:
## BEFORE FINETUNING
test_data = ["""Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Amisha Dixit
Date of Birth: October 13, 1994
Gender: Female
Address: 1b003, Suncity Gloria, Bangalore, India
Phone Number: (91) 1289024802
Email: amishadixit2738@email.com

Dependents:
1. Full Name: Aarav Dixit
Date of Birth: November 12, 2017
Gender: Male
Relationship: Son
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Jassi Madhav
Last Medical Checkup Date: July 25, 2023
Medical Conditions: None
Allergies: None

Medications:
Medication Name: None
Dosage: N/A
Frequency: N/A

Hospitalizations:
Hospital Name: Lakshmi Medical Center
Reason: None
Date: N/A
Surgeries:

Surgery Type: None ->:
"""]

sequences = pipeline(
    test_data,
    max_length=512,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

0 Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Amisha Dixit
Date of Birth: October 13, 1994
Gender: Female
Address: 1b003, Suncity Gloria, Bangalore, India
Phone Number: (91) 1289024802
Email: amishadixit2738@email.com

Dependents:
1. Full Name: Aarav Dixit
Date of Birth: November 12, 2017
Gender: Male
Relationship: Son
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Jassi Madhav
Last Medical Checkup Date: July 25, 2023
Medical Conditions: None
Allergies: None

Medications:
Medication Name: None
Dosage: N/A
Frequency: N/A

Hospitalizations:
Hospital Name: Lakshmi Medical Center
Reason: None
Date: N/A
Surgeries:

Surgery Type: None ->:
Surgery Reason: None ->:
Surgeon: None
Outpatient Procedures:
Procedure Name: None
Procedure Reason: None <-:
Physician: None

Dental Procedures:
Dentist Name: None
Dental Procedures performed: N/A

Vision Procedures:
Optometrist Name: Dr. Aman
LASIK/PRK: None
Lens Type: None

Mental Health History:
Psychiatric Medications:
Medication Name: None
Frequency: N/A

Psychiatrist: Dr. Vijay Sharan
Psychologist: None
Social Worker: None

Alcohol and Drug History:
Alcohol and Drug Treatments: None
Drug and Alcohol Treatment Facility: None
Outpatient Drug and Alcohol Rehab: None

Other Conditions/Treatment:

In [ ]:
## BEFORE FINETUNING
test_data = ["""Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Lisa Johnson
Date of Birth: July 12, 1972
Gender: Female
Address: 789 Elm Street, Harborview, CA
Phone Number: (555) 987-6543
Email: lisa.johnson@email.com
Occupation: Marketing Manager

Dependents:

1.Full Name: Jack Johnson
Date of Birth: May 20, 2009
Gender: Male
Relationship: Son
Dependent Type: Child

2. Full Name: Jasmine Johnson
Date of Birth: May 20, 2009
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Sarah Lewis
Last Medical Checkup Date: August 28, 2023

Medical Conditions: None

Allergies: None

Medications:

Medication Name: None
Dosage: N/A
Frequency: N/A
Hospitalizations:

Hospital Name: Harborview Medical Center
Reason: None
Date: N/A
Surgeries:

Surgery Type: None ->:
"""]

sequences = pipeline(
    test_data,
    max_length=512,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

0 Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Lisa Johnson
Date of Birth: July 12, 1972
Gender: Female
Address: 789 Elm Street, Harborview, CA
Phone Number: (555) 987-6543
Email: lisa.johnson@email.com
Occupation: Marketing Manager

Dependents:

1.Full Name: Jack Johnson
Date of Birth: May 20, 2009
Gender: Male
Relationship: Son
Dependent Type: Child

2. Full Name: Jasmine Johnson
Date of Birth: May 20, 2009
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Sarah Lewis
Last Medical Checkup Date: August 28, 2023

Medical Conditions: None

Allergies: None

Medications:

Medication Name: None
Dosage: N/A
Frequency: N/A
Hospitalizations:

Hospital Name: Harborview Medical Center
Reason: None
Date: N/A
Surgeries:

Surgery Type: None ->:
Date: N/A
Surgeon: Dr. Sarah Lewis

Medical History Notes:

Notes:


**Note:** These are the sample input data. You have to write the function to extract all these data.

In [ ]:
## BEFORE FINETUNING
test_data = ["""Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Michelle Anderson
Date of Birth: June 5, 1970
Gender: Female
Address: 123 Oakwood Drive, Green Hills, CA
Phone Number: (555) 123-4567
Email: michelle.anderson@email.com
Occupation: Registered Nurse

Dependents:
Spouse:
Full Name: David Anderson
Date of Birth: August 15, 1968
Gender: Male
Relationship: Husband
Dependent Type: Adult

Child:
Full Name: Emily Anderson
Date of Birth: November 20, 1995
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Rachel Smith
Last Medical Checkup Date: August 5, 2023
Medical Conditions:
Hypertension
Diagnosis Date: January 5, 2010
Treatment: Medication (Lisinopril)
Asthma
Diagnosis Date: August 15, 2000
Treatment: Inhalers (Albuterol and Advair)
Allergies: None

Medications:
Medication Name: Lisinopril (for hypertension)
Dosage: 10 mg daily
Frequency: Daily
Medication Name: Albuterol (for asthma)
Dosage: As needed
Frequency: As needed
Medication Name: Advair (for asthma)
Dosage: As prescribed
Frequency: As prescribed

Hospitalizations:
Hospital Name: Green Hills General Hospital
Reason: Appendectomy
Date: March 20, 1992

Surgeries:

Surgery Type: Appendectomy
Date: March 20, 1992 ->:
"""]

sequences = pipeline(
    test_data,
    max_length=800,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

0 Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Michelle Anderson
Date of Birth: June 5, 1970
Gender: Female
Address: 123 Oakwood Drive, Green Hills, CA
Phone Number: (555) 123-4567
Email: michelle.anderson@email.com
Occupation: Registered Nurse

Dependents:
Spouse:
Full Name: David Anderson
Date of Birth: August 15, 1968
Gender: Male
Relationship: Husband
Dependent Type: Adult

Child:
Full Name: Emily Anderson
Date of Birth: November 20, 1995
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Rachel Smith
Last Medical Checkup Date: August 5, 2023
Medical Conditions:
Hypertension
Diagnosis Date: January 5, 2010
Treatment: Medication (Lisinopril)
Asthma
Diagnosis Date: August 15, 2000
Treatment: Inhalers (Albuterol and Advair)
Allergies: None

Medications:
Medication Name: Lisinopril (for hypertension)
Dosage: 10 mg daily
Frequency: Daily
Medication Name: Albuterol (for asthma)
Dosage: As needed
Frequency: As needed
Medication Name: Advair (for asthma)
Dosage: As prescribed
Frequency: As prescribed

Hospitalizations:
Hospital Name: Green Hills General Hospital
Reason: Appendectomy
Date: March 20, 1992

Surgeries:

Surgery Type: Appendectomy
Date: March 20, 1992 ->:
Surgeon: Dr. Robert Smith
Skin Type: Normal
Skin Tone: Medium (5)
```

### 20. What should be the output for the above input?

```
Output

Insured: Michelle Anderson
Policy Number: 2020123
Policy Effective Date: August 1, 2020
Policy Expires: August 31, 2023

Underwriting Information

Gender: Female
Age: 50
Date of Birth: June 5, 1970

Marital Status: Single
Relationship: Marital Status: Single
Spouse: David Anderson
Child: Emily Anderson
Adult Dependent: David Anderson
Child Dependent: Emily Anderson

Medical History

Diagnoses:
Hypertension
Diagnosis Date: January 5, 2010
Treatment: Medication (Lisinopril)
Asthma
Diagnosis Date: August 15, 2000
Treatment: Inhalers (Albuterol and Advair)

Medications
Medication Name: Lisinopril (for hypertension)
Dosage: 10 mg daily
Frequency: Daily
Medication Name: Al

In [ ]:
## BEFORE FINETUNING
test_data = ["""Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Rishika Thakur
Date of Birth: November 15, 1990
Gender: Female
Address: 154, Sunpharma Road, Vadodara
Phone Number: +91 8473894725
Email: ririthakur3@email.com
Occupation: Doctor

Dependents:
Spouse:
Full Name: Dhruv Thakur
Date of Birth: June 21, 1988
Gender: Male
Relationship: Husband
Dependent Type: Adult

Child:
Full Name: Esha Thakur
Date of Birth: November 12, 2020
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:

Primary Care Physician: Dr. Rakhi Sharma
Last Medical Checkup Date: August 5, 2023
Medical Conditions:
Type 2 Diabetes
Diagnosis Date: June 10, 2015
Treatment: Insulin and Metformin
Arthritis
Diagnosis Date: November 8, 2005
Treatment: Nonsteroidal Anti-Inflammatory Drugs (NSAIDs)
Allergies: None

Medications:
Medication Name: Insulin (for diabetes)
Dosage: As prescribed
Frequency: As prescribed
Medication Name: Metformin (for diabetes)
Dosage: 500 mg twice daily
Frequency: Daily
Medication Name: Ibuprofen (for arthritis)
Dosage: 400 mg as needed
Frequency: As needed
Hospitalizations:

Hospital Name: Green Hills General Hospital
Reason: Knee Replacement Surgery
Date: May 8, 2018
Hospital Name: Green Hills General Hospital
Reason: Gallbladder Removal Surgery
Date: June 15, 2022
Surgeries:

Surgery Type: Knee Replacement Surgery
Date: May 8, 2018
Surgery Type: Gallbladder Removal Surgery
Date: June 15, 2022 ->:
"""]

sequences = pipeline(
    test_data,
    max_length=800,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

0 Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Rishika Thakur
Date of Birth: November 15, 1990
Gender: Female
Address: 154, Sunpharma Road, Vadodara
Phone Number: +91 8473894725
Email: ririthakur3@email.com
Occupation: Doctor

Dependents:
Spouse:
Full Name: Dhruv Thakur
Date of Birth: June 21, 1988
Gender: Male
Relationship: Husband
Dependent Type: Adult

Child:
Full Name: Esha Thakur
Date of Birth: November 12, 2020
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:

Primary Care Physician: Dr. Rakhi Sharma
Last Medical Checkup Date: August 5, 2023
Medical Conditions:
Type 2 Diabetes
Diagnosis Date: June 10, 2015
Treatment: Insulin and Metformin
Arthritis
Diagnosis Date: November 8, 2005
Treatment: Nonsteroidal Anti-Inflammatory Drugs (NSAIDs)
Allergies: None

Medications:
Medication Name: Insulin (for diabetes)
Dosage: As prescribed
Frequency: As prescribed
Medication Name: Metformin (for diabetes)
Dosage: 500 mg twice daily
Frequency: Daily
Medication Name: Ibuprofen (for arthritis)
Dosage: 400 mg as needed
Frequency: As needed
Hospitalizations:

Hospital Name: Green Hills General Hospital
Reason: Knee Replacement Surgery
Date: May 8, 2018
Hospital Name: Green Hills General Hospital
Reason: Gallbladder Removal Surgery
Date: June 15, 2022
Surgeries:

Surgery Type: Knee Replacement Surgery
Date: May 8, 2018
Surgery Type: Gallbladder Removal Surgery
Date: June 15, 2022 ->:

## 3.2.2. Insurance underwriting

> Note: We recommend you to use a real insurance provider's website as a source of inspiration for your solution.

## 3.2.3. Insurance underwriting results

> Note: We recommend you to use the [insurances](https://github.com/insurances) GitHub repository as a source of inspiration for your solution.

## 4. Bonus

### 4.1. Rating

> Note: We recommend you to use the [rating](https://github.com/rating) GitHub repository as a source of inspiration for your solution.

### 4.2. Fuel Price Predictor

> Note: We recommend you to use the [fuel-predictor](https://github.com/fuel-predictor) GitHub repository as a source of inspiration for your solution.

###

In [ ]:
## BEFORE FINETUNING
test_data = ["""Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Kevin Walker
Date of Birth: April 30, 1985
Gender: Male
Address: 456 Maple Street, Riverside, FL
Phone Number: (555) 789-1234
Email: kevin.walker@email.com
Occupation: Electrician

Dependents:

Spouse:
Full Name: Jessica Walker
Date of Birth: September 20, 1987
Gender: Female
Relationship: Wife
Dependent Type: Adult

Medical History:
Primary Care Physician: Dr. Thomas Brown
Last Medical Checkup Date: August 10, 2023
Medical Conditions:
Chronic Back Pain
Diagnosis Date: July 5, 2015
Treatment: Physical Therapy and Pain Medication
Migraine Headaches
Diagnosis Date: April 15, 2007
Treatment: Triptans and Lifestyle Management
Allergies: None

Medications:
Medication Name: Naproxen (for back pain)
Dosage: 500 mg twice daily
Frequency: Daily
Medication Name: Sumatriptan (for migraines)
Dosage: 100 mg as needed
Frequency: As needed
Hospitalizations 8:

Hospital Name: Riverside Medical Center
Reason: Appendectomy
Date: February 18, 2010

Surgeries:
None ->:
"""]

sequences = pipeline(
    test_data,
    max_length=800,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1417: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation )
  warnings.warn(

0 Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Kevin Walker
Date of Birth: April 30, 1985
Gender: Male
Address: 456 Maple Street, Riverside, FL
Phone Number: (555) 789-1234
Email: kevin.walker@email.com
Occupation: Electrician

Dependents:

Spouse:
Full Name: Jessica Walker
Date of Birth: September 20, 1987
Gender: Female
Relationship: Wife
Dependent Type: Adult

Medical History:
Primary Care Physician: Dr. Thomas Brown
Last Medical Checkup Date: August 10, 2023
Medical Conditions:
Chronic Back Pain
Diagnosis Date: July 5, 2015
Treatment: Physical Therapy and Pain Medication
Migraine Headaches
Diagnosis Date: April 15, 2007
Treatment: Triptans and Lifestyle Management
Allergies: None

Medications:
Medication Name: Naproxen (for back pain)
Dosage: 500 mg twice daily
Frequency: Daily
Medication Name: Sumatriptan (for migraines)
Dosage: 100 mg as needed
Frequency: As needed
Hospitalizations 8:

Hospital Name: Riverside Medical Center
Reason: Appendectomy
Date: February 18, 2010

Surgeries:
None ->:

Mental Health Disorders:
Depression: Diagnosis Date: February 2, 2009
Treatment: Antidepressants

Social Determinants of Health (SDoH):

Education: High School Diploma, Riverside High School, Riverside, FL
Education Date: August 1, 2007 to August 1, 2011

Household Income:
Gross Household Income: $6,000
Net Household Income: $3,285

Transportation:
No Vehicle

Housing:
Rental

Food Security:
Lacks consistent access to adequate nutritious food ->

Utility Assistance:
Lacks consistent access to utilities

Other SDoHs:
None

In [ ]:
## BEFORE FINETUNING
test_data = ["""Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Lisa Martinez
Date of Birth: October 12, 1982
Gender: Female
Address: 789 Cedar Avenue, Oakville, NY
Phone Number: (555) 123-4567
Email: lisa.martinez@email.com
Occupation: Pediatrician

Dependents:
Spouse:
Full Name: Carlos Martinez
Date of Birth: December 5, 1980
Gender: Male
Relationship: Husband
Dependent Type: Adult

Child:
Name: Ashley Martinez
Date of Birth: August 23 2010
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Jennifer Adams
Last Medical Checkup Date: September 5, 2023
Medical Conditions:
Asthma
Diagnosis Date: January 10, 1990
Treatment: Inhalers (Albuterol and Advair)
Allergic Rhinitis (Hay Fever)
Diagnosis Date: April 15, 2005
Treatment: Antihistamines
Allergies:
Allergy: Penicillin
Severity: Moderate

Medications:
Medication Name: Albuterol (for asthma)
Dosage: As needed
Frequency: As needed
Medication Name: Advair (for asthma)
Dosage: As prescribed
Frequency: As prescribed
Medication Name: Loratadine (for allergies)
Dosage: 10 mg daily
Frequency: Daily

Hospitalizations:
Hospital Name: Oakville General Hospital
Reason: Kidney Stone
Date: N/A

Surgeries:
Surgery Type: Kidney Stone Removal
Date of Admission: January 19 2007 ->:
"""]

sequences = pipeline(
    test_data,
    max_length=800,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

0 Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Lisa Martinez
Date of Birth: October 12, 1982
Gender: Female
Address: 789 Cedar Avenue, Oakville, NY
Phone Number: (555) 123-4567
Email: lisa.martinez@email.com
Occupation: Pediatrician

Dependents:
Spouse:
Full Name: Carlos Martinez
Date of Birth: December 5, 1980
Gender: Male
Relationship: Husband
Dependent Type: Adult

Child:
Name: Ashley Martinez
Date of Birth: August 23 2010
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Jennifer Adams
Last Medical Checkup Date: September 5, 2023
Medical Conditions:
Asthma
Diagnosis Date: January 10, 1990
Treatment: Inhalers (Albuterol and Advair)
Allergic Rhinitis (Hay Fever)
Diagnosis Date: April 15, 2005
Treatment: Antihistamines
Allergies:
Allergy: Penicillin
Severity: Moderate

Medications:
Medication Name: Albuterol (for asthma)
Dosage: As needed
Frequency: As needed
Medication Name: Advair (for asthma)
Dosage: As prescribed
Frequency: As prescribed
Medication Name: Loratadine (for allergies)
Dosage: 10 mg daily
Frequency: Daily

Hospitalizations:
Hospital Name: Oakville General Hospital
Reason: Kidney Stone
Date: N/A

Surgeries:
Surgery Type: Kidney Stone Removal
Date of Admission: January 19 2007 ->:
Hospital Name: Oakville General Hospital
Reason: Kidney stones
Date: January 19, 2007

Discharge Summary:
Date of Admission: January 19 2007
Age: 26 years old
Reason: Kidney stones
Hospital: Oakville General Hospital
Diagnosis: Ureterolith

Procedure:
1. Extracorporeal shockwave lithotripsy
2. Intravenous pyelography
3. Intravenous Pyelography with Ureterolithotomy

Date of Admission: January 19 2003
Age: 26 years old

Reason: Kidney stones
Hospital: Oakville General Hospital
Diagnosis: Kidney and ureter stones

Procedure:
1. Extracorporeal shockwave lithotripsy
2. Ureterostomy with ureteroscopy
3. Intravenous Pyelography

Date of Admission: March 23, 2011
Age: 27 years old

Reason: Asthma Attack
Hospital: Oakville General Hospital
Diagnosis: Asthma Exacerbation

In [ ]:
## BEFORE FINETUNING
test_data = ["""Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Daniel Lee
Date of Birth: July 20, 1978
Gender: Male
Address: 321 Elm Street, Pineville, TX
Phone Number: (555) 987-6543
Email: daniel.lee@email.com
Occupation: Architect

Dependents:
Spouse:
Full Name: Laura Lee
Date of Birth: March 10, 1982
Gender: Female
Relationship: Wife
Dependent Type: Adult

Child 1:
Full Name: Ethan Lee
Date of Birth: December 15, 2010
Gender: Male
Relationship: Son
Dependent Type: Child

Child 2:
Full Name: Ema Lee
Date of Birth: April 06, 2007
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Susan Wilson
Last Medical Checkup Date: July 10, 2023
Medical Conditions:
Type 2 Diabetes
Diagnosis Date: May 5, 2012
Treatment: Metformin and Dietary Management
High Cholesterol (Hypercholesterolemia)
Diagnosis Date: October 20, 2018
Treatment: Statins (Atorvastatin)
Allergies: None

Medications:
Medication Name: Metformin (for diabetes)
Dosage: 500 mg twice daily
Frequency: Daily
Medication Name: Atorvastatin (for high cholesterol)
Dosage: 20 mg daily
Frequency: Daily

Hospitalizations:
Hospital Name: Pineville Medical Center
Reason: Fever
Date: N/A

Surgeries:
Surgery Type: None ->:
"""]

sequences = pipeline(
    test_data,
    max_length=800,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

0 Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Daniel Lee
Date of Birth: July 20, 1978
Gender: Male
Address: 321 Elm Street, Pineville, TX
Phone Number: (555) 987-6543
Email: daniel.lee@email.com
Occupation: Architect

Dependents:
Spouse:
Full Name: Laura Lee
Date of Birth: March 10, 1982
Gender: Female
Relationship: Wife
Dependent Type: Adult

Child 1:
Full Name: Ethan Lee
Date of Birth: December 15, 2010
Gender: Male
Relationship: Son
Dependent Type: Child

Child 2:
Full Name: Ema Lee
Date of Birth: April 06, 2007
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Susan Wilson
Last Medical Checkup Date: July 10, 2023
Medical Conditions:
Type 2 Diabetes
Diagnosis Date: May 5, 2012
Treatment: Metformin and Dietary Management
High Cholesterol (Hypercholesterolemia)
Diagnosis Date: October 20, 2018
Treatment: Statins (Atorvastatin)
Allergies: None

Medications:
Medication Name: Metformin (for diabetes)
Dosage: 500 mg twice daily
Frequency: Daily
Medication Name: Atorvastatin (for high cholesterol)
Dosage: 20 mg daily
Frequency: Daily

Hospitalizations:
Hospital Name: Pineville Medical Center
Reason: Fever
Date: N/A

Surgeries:
Surgery Type: None ->:
Reason: None

Doctor: Dr. Wilson
Specialty: Internal Medicine
Specialty Code: 207

Specialty: Cardiology
Specialty Code: 209

Specialty: Gastroenterology
Specialty Code: 223

Specialty: Neurology
Specialty Code: 260

Specialty: Oncology
Specialty Code: 272

Specialty: Pulmonary Disease
Specialty Code: 357

Specialty: Rheumatology
Speciality Code: 471

Specialty: Endocrinology
Specialty Code: 585

Specialty: Nephrology
Specialty Code: 890

Specialty: Ophthalmology
Specialty Code: 811

Specialty: Orthopedics
Specialty Code: 832

Specialty: Psychiatry
Specialty Code: 965
\end{code}

The output of the code is:

\begin{code}
{
    "id": "1",
    "type": ["10033", "44055", "11994", "42289"],
    "primary_care

In [ ]:
## BEFORE FINETUNING
test_data = ["""Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Rachel Turner
Date of Birth: November 8, 1990
Gender: Female
Address: 789 Birch Road, Harborview, CA
Phone Number: (555) 123-7890
Email: rachel.turner@email.com
Occupation: Software Developer

Dependents:
Spouse:
Full Name: Matthew Turner
Date of Birth: April 15, 1992
Gender: Male
Relationship: Husband
Dependent Type: Adult


Medical History:
Rachel Turner
Primary Care Physician: Dr. Emily Harris
Last Medical Checkup Date: August 15, 2023
Medical Conditions:
Anxiety Disorder
Diagnosis Date: June 5, 2015
Treatment: Cognitive-Behavioral Therapy and Medication (SSRIs)
Seasonal Affective Disorder (SAD)
Diagnosis Date: December 10, 2012
Treatment: Light Therapy and Lifestyle Management
Allergies: None

Medications:
Medication Name: Sertraline (for anxiety)
Dosage: 50 mg daily
Frequency: Daily

Hospitalizations:
Hospital Name: Harborview General Hospital
Reason: None
Date: N/A

Surgeries:

Surgery Type: None

Matthew Turner
Primary Care Physician: Dr. Emily Harris
Last Medical Checkup Date: August 15, 2023
- No pre-existing medical conditions
- Hospitalized for pneumonia in 2016, fully recovered
- No chronic illnesses or disabilities ->:
"""]

sequences = pipeline(
    test_data,
    max_length=800,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

0 Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Rachel Turner
Date of Birth: November 8, 1990
Gender: Female
Address: 789 Birch Road, Harborview, CA
Phone Number: (555) 123-7890
Email: rachel.turner@email.com
Occupation: Software Developer

Dependents:
Spouse:
Full Name: Matthew Turner
Date of Birth: April 15, 1992
Gender: Male
Relationship: Husband
Dependent Type: Adult


Medical History:
Rachel Turner
Primary Care Physician: Dr. Emily Harris
Last Medical Checkup Date: August 15, 2023
Medical Conditions:
Anxiety Disorder
Diagnosis Date: June 5, 2015
Treatment: Cognitive-Behavioral Therapy and Medication (SSRIs)
Seasonal Affective Disorder (SAD)
Diagnosis Date: December 10, 2012
Treatment: Light Therapy and Lifestyle Management
Allergies: None

Medications:
Medication Name: Sertraline (for anxiety)
Dosage: 50 mg daily
Frequency: Daily

Hospitalizations:
Hospital Name: Harborview General Hospital
Reason: None
Date: N/A

Surgeries:

Surgery Type: None

Matthew Turner
Primary Care Physician: Dr. Emily Harris
Last Medical Checkup Date: August 15, 2023
- No pre-existing medical conditions
- Hospitalized for pneumonia in 2016, fully recovered
- No chronic illnesses or disabilities ->:

Rachel Turner
Primary Care Physician: Dr. Emily Harris
Last Medical Checkup Date: August 15, 2023

Rachel Turner
Primary Care Physician: Dr. Emily Harris
Last Medical Checkup Date: August 15, 2023
- No pre-existing medical conditions
- Hospitalized for pneumonia in 2016, fully recovered
- No chronic illnesses or disabilities

Matthew Turner
Primary Care Physician: Dr. Emily Harris



Medications:
- Sertraline (for anxiety) Dosage: 50 mg daily
- Frequency (per day): Daily

Matthew Turner
Primary Care Physician: Dr. Emily Harris
Last Medical Checkup Date: August 15, 2023
- No pre-existing medical conditions
- Hospitalized for pneumonia in 2016, fully recovered
- No chronic illnesses or disabilities

Matthew Turner
Primary Care Physician: Dr. Emily Harris
Last Medical Checkup Date: August 15, 2023

```

- 5.02.06 사람이 가지는 특징들을 받아들이고 닥스테론은 적절한 닥스테론 분류와

In [ ]:
## BEFORE FINETUNING
test_data = ["""Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Samuel Harris
Date of Birth: March 25, 1986
Gender: Male
Address: 456 Spruce Street, Woodville, TX
Phone Number: (555) 456-7891
Email: samuel.harris@email.com
Occupation: Accountant

Dependents:
Spouse:
Full Name: Olivia Harris
Date of Birth: October 20, 1988
Gender: Female
Relationship: Wife
Dependent Type: Adult

Child:
Full Name: Phoebe Harris
Date of Birth: December 12, 2012
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Samuel Harris
Primary Care Physician: Dr. Michael Turner
Last Medical Checkup Date: September 20, 2023
Medical Conditions:
Asthma
Diagnosis Date: January 5, 1995
Treatment: Inhalers (Albuterol and Advair)
GERD (Gastroesophageal Reflux Disease)
Diagnosis Date: April 15, 2010
Treatment: Proton Pump Inhibitors (PPIs)
Allergies:
Allergy: Shellfish
Severity: Moderate
Medications 12:

Medication Name: Albuterol (for asthma)
Dosage: As needed
Frequency: As needed
Medication Name: Advair (for asthma)
Dosage: As prescribed
Frequency: As prescribed
Medication Name: Omeprazole (for GERD)
Dosage: 20 mg daily
Frequency: Daily

Hospitalizations:
Hospital Name: Woodville Regional Hospital
Reason: Asthma
Date: February 22, 2015

Surgeries:
Surgery Type: None

Olivia Harris
Primary Care Physician: Dr. Michael Turner
Last Medical Checkup Date: March 18, 2023

Medical Conditions:
Anxiety Disorder
Diagnosis Date: June 5, 2015
Treatment: Cognitive-Behavioral Therapy and Medication (SSRIs)

Medications:
Medication Name: Sertraline (for anxiety)
Dosage: 50 mg daily
Frequency: Daily

Phoebe Harris:
- No major health conditions or surgeries in the past 5 years
- Prescription medications: None ->:
"""]

sequences = pipeline(
    test_data,
    max_length=800,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

0 Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Samuel Harris
Date of Birth: March 25, 1986
Gender: Male
Address: 456 Spruce Street, Woodville, TX
Phone Number: (555) 456-7891
Email: samuel.harris@email.com
Occupation: Accountant

Dependents:
Spouse:
Full Name: Olivia Harris
Date of Birth: October 20, 1988
Gender: Female
Relationship: Wife
Dependent Type: Adult

Child:
Full Name: Phoebe Harris
Date of Birth: December 12, 2012
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Samuel Harris
Primary Care Physician: Dr. Michael Turner
Last Medical Checkup Date: September 20, 2023
Medical Conditions:
Asthma
Diagnosis Date: January 5, 1995
Treatment: Inhalers (Albuterol and Advair)
GERD (Gastroesophageal Reflux Disease)
Diagnosis Date: April 15, 2010
Treatment: Proton Pump Inhibitors (PPIs)
Allergies:
Allergy: Shellfish
Severity: Moderate
Medications 12:

Medication Name: Albuterol (for asthma)
Dosage: As needed
Frequency: As needed
Medication Name: Advair (for asthma)
Dosage: As prescribed
Frequency: As prescribed
Medication Name: Omeprazole (for GERD)
Dosage: 20 mg daily
Frequency: Daily

Hospitalizations:
Hospital Name: Woodville Regional Hospital
Reason: Asthma
Date: February 22, 2015

Surgeries:
Surgery Type: None

Olivia Harris
Primary Care Physician: Dr. Michael Turner
Last Medical Checkup Date: March 18, 2023

Medical Conditions:
Anxiety Disorder
Diagnosis Date: June 5, 2015
Treatment: Cognitive-Behavioral Therapy and Medication (SSRIs)

Medications:
Medication Name: Sertraline (for anxiety)
Dosage: 50 mg daily
Frequency: Daily

Phoebe Harris:
- No major health conditions or surgeries in the past 5 years
- Prescription medications: None ->:

Medical History:
Samuel Harris -> Olivia Harris:

Medications 12:

Medication Name: Albuterol (for asthma)
Dosage: As needed
Frequency: As needed
Medication Name: Advair (for asthma)
Dosage: As prescribed
Frequency: As prescribed
Medication Name: Omeprazole (for GERD)
Dosage: 20 mg daily
Frequency: Daily

Olivia Harris -> Phoebe Harris:
Medical History:

**FINETUNING THE MODEL**

In [ ]:
from peft import LoraConfig

lora_alpha = 16
lora_dropout = 0.1
lora_r = 64

peft_config = LoraConfig(
    lora_alpha=lora_alpha,
    lora_dropout=lora_dropout,
    r=lora_r,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj","v_proj"]
)

In [ ]:
from transformers import TrainingArguments

output_dir = "./insurance_results"
per_device_train_batch_size = 4
gradient_accumulation_steps = 4
optim = "paged_adamw_32bit"
save_steps = 10
logging_steps = 1
learning_rate = 2e-4
max_grad_norm = 0.3
max_steps = 120
warmup_ratio = 0.03
lr_scheduler_type = "constant"

training_arguments = TrainingArguments(
    output_dir=output_dir,
    per_device_train_batch_size=per_device_train_batch_size,
    gradient_accumulation_steps=gradient_accumulation_steps,
    optim=optim,
    save_steps=save_steps,
    logging_steps=logging_steps,
    learning_rate=learning_rate,
    fp16=True,
    max_grad_norm=max_grad_norm,
    max_steps=max_steps,
    warmup_ratio=warmup_ratio,
    group_by_length=True,
    lr_scheduler_type=lr_scheduler_type,
)

In [ ]:
from trl import SFTTrainer

max_seq_length = 512

trainer = SFTTrainer(
    model=model,
    train_dataset=train_dataset_dict['train'],
    # train_dataset=data['train'],
    peft_config=peft_config,
    dataset_text_field="text",
    # dataset_text_field="prediction",
    max_seq_length=max_seq_length,
    tokenizer=tokenizer,
    args=training_arguments,
)

/usr/local/lib/python3.10/dist-packages/peft/utils/other.py:133: FutureWarning: prepare_model_for_int8_training is deprecated and will be removed in a future version. Use prepare_model_for_kbit_training instead.
  warnings.warn(

Map:   0%|          | 0/26120 [00:00<?, ? examples/s]

/usr/local/lib/python3.10/dist-packages/trl/trainer/sft_trainer.py:207: UserWarning: You passed a tokenizer with `padding_side` not equal to `right` to the SFTTrainer. This might lead to some unexpected behaviour due to overflow issues when training a model in half-precision. You might consider adding `tokenizer.padding_side = 'right'` to your code.
  warnings.warn(

In [ ]:
import locale
def getpreferredencoding(do_setlocale = True):
    return "UTF-8"
locale.getpreferredencoding = getpreferredencoding

In [ ]:
for name, module in trainer.model.named_modules():
    if "norm" in name:
        module = module.to(torch.float32)

In [ ]:
! wandb login 942c0bdca2f1b19b6cef0464f048c21bfdf93c24

wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc

In [ ]:
trainer.train()

wandb: Currently logged in as: stuti-srivastava. Use `wandb login --relogin` to force relogin

You're using a LlamaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

TrainOutput(global_step=120, training_loss=0.43955542674909037, metrics={'train_runtime': 2963.9943, 'train_samples_per_second': 0.648, 'train_steps_per_second': 0.04, 'total_flos': 1.94467302875136e+16, 'train_loss': 0.43955542674909037, 'epoch': 0.07})

In [35]:
test_df['test_text'] = test_df.apply(lambda row: row['input_text'] + " ->: ", axis = 1)
lst_test_data = list(test_df['test_text'])

In [36]:
len(lst_test_data)

6531

In [37]:
sample_size = 10
lst_test_data_short = lst_test_data[:sample_size]

In [ ]:
import transformers

pipeline = transformers.pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    # torch_dtype=torch.bfloat16,
    torch_dtype=torch.float16,
    trust_remote_code=True,
    device_map="auto",
)

In [38]:
sequences = pipeline(
    lst_test_data_short,
    max_length=1024,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

/usr/local/lib/python3.10/dist-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")

KeyboardInterrupt: ignored

In [ ]:
test_data = ["""Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Name: Ayesha Nomani
Date of Birth: November 28, 1990
Gender: Female
Address: 123, Sarjapura Road, Bengaluru
Phone Number: +91 987654321
Email: nomani.ayesha@gmail.com
Occupation: Elementary School Teacher

Dependents:
1. Name: Firoz Nomani
Date of Birth: February 22, 1990
Gender: Male
Relationship: Husband

2. Name: Saya Nomani
Date of Birth: June 12, 2019
Relationship: Child

Medical History:
Primary Care Physician: Dr. Jyoti Awasthi
Last Medical Checkup Date: May 11, 2023
Medical Conditions: None

Allergies:
Allergy: Penicillin
Severity: Moderate

Medications:
Medication Name: None
Dosage: N/A
Frequency: N/A

Hospitalizations:
Hospital Name: Springfield Medical Center
Reason: Leg Surgery
Date: June 15, 2015

Firoz Nomani
- Asthma diagnosis in 2010, but well-controlled with medication
- Non-smoker
- No history of serious illnesses

Saya Nomani
- Overall good health
- No known allergies or pre-existing medical conditions
- Non-smoker
- No history of serious illnesses
->:
"""]

sequences = pipeline(
    test_data,
    max_length=512,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

0 Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Name: Ayesha Nomani
Date of Birth: November 28, 1990
Gender: Female
Address: 123, Sarjapura Road, Bengaluru
Phone Number: +91 987654321
Email: nomani.ayesha@gmail.com
Occupation: Elementary School Teacher

Dependents:
1. Name: Firoz Nomani
Date of Birth: February 22, 1990
Gender: Male
Relationship: Husband

2. Name: Saya Nomani
Date of Birth: June 12, 2019
Relationship: Child

Medical History:
Primary Care Physician: Dr. Jyoti Awasthi
Last Medical Checkup Date: May 11, 2023
Medical Conditions: None

Allergies:
Allergy: Penicillin
Severity: Moderate

Medications:
Medication Name: None
Dosage: N/A
Frequency: N/A

Hospitalizations:
Hospital Name: Springfield Medical Center
Reason: Leg Surgery
Date: June 15, 2015 ->:
Hospitalization Details:
- Admission Date: June 15, 2015
- Discharge Date: June 21, 2015
- Length of Stay (in Days): 6
- Reason for Stay: Leg Surgery
- Surgeon: Dr. S.P. Singh

 ->:

Policy Details:
- Coverage Type: Comprehensive
- Premium: Rs. 10,000
- Deductible: Rs. 10,000
- Maximum Coverage: Rs. 10,00,000
- Co-Payment: 20% of the Medical Expenses


Coverage Areas:
- Inpatient Treatment

In [ ]:
## AFTER FINETUNING
test_data = ["""Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Jason Pitt
Date of Birth: May 25, 1981
Gender: Male
Address: 753, Richmond Street, California, USA
Phone Number: (555) 682920
Email: jason.pitt218@email.com
Occupation: Software Engineer

Dependents:
1. Name: Emma Pitt
Date of Birth: January 22, 1982
Gender: Female
Relationship: Wife
Dependent Type: Adult

2. Name: Emily Pitt
Date of Birth: June 12, 2005
Relationship: Child
Gender: Female

Medical History:
Primary Care Physician: Dr. Lisa Johnson

Last Medical Checkup Date: May 15, 2023

Medical Conditions: None

Allergies: None

Medications:

Medication Name: None
Dosage: N/A
Frequency: N/A
Hospitalizations:

Hospital Name: Anytown General Hospital
Reason: Appendectomy
Date: March 5, 2019
Surgeries:

Surgery Type: None ->:
"""]

sequences = pipeline(
    test_data,
    max_length=800,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

0 Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Jason Pitt
Date of Birth: May 25, 1981
Gender: Male
Address: 753, Richmond Street, California, USA
Phone Number: (555) 682920
Email: jason.pitt218@email.com
Occupation: Software Engineer

Dependents:
1. Name: Emma Pitt
Date of Birth: January 22, 1982
Gender: Female
Relationship: Wife
Dependent Type: Adult

2. Name: Emily Pitt
Date of Birth: June 12, 2005
Relationship: Child
Gender: Female

Medical History:
Primary Care Physician: Dr. Lisa Johnson

Last Medical Checkup Date: May 15, 2023

Medical Conditions: None

Allergies: None

Medications:

Medication Name: None
Dosage: N/A
Frequency: N/A
Hospitalizations:

Hospital Name: Anytown General Hospital
Reason: Appendectomy
Date: March 5, 2019
Surgeries:

Surgery Type: None ->:
Name of Surgeon: Dr. Smith
Hospital Name: None
Date: June 17, 2022
Hospitalizations:

Hospital Name: Anytown General Hospital
Reason: None
Date: March 15, 2015
Surgeries:
Surgery Type: None
Name Of Surgeon: Dr. Anderson
Hospital Name: Anytown Medical Centre
Date: May 26, 2018


Policy Details:
Policy Type: Health Insurance Policy
Policy Expiration Date: January 1, 2029
Policy Limit: $500,000
Annual Deductible: $500
Co-payments:

- Doctor visits: $30 per visit
- Prescription medications: Generic -

In [ ]:
## AFTER FINETUNING
test_data = ["""0 Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Michelle Anderson
Date of Birth: June 5, 1970
Gender: Female
Address: 123 Oakwood Drive, Green Hills, CA
Phone Number: (555) 123-4567
Email: michelle.anderson@email.com
Occupation: Registered Nurse

Dependents:
Spouse:
Full Name: David Anderson
Date of Birth: August 15, 1968
Gender: Male
Relationship: Husband
Dependent Type: Adult

Child:
Full Name: Emily Anderson
Date of Birth: November 20, 1995
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Rachel Smith
Last Medical Checkup Date: August 5, 2023
Medical Conditions:
Hypertension
Diagnosis Date: January 5, 2010
Treatment: Medication (Lisinopril)
Asthma
Diagnosis Date: August 15, 2000
Treatment: Inhalers (Albuterol and Advair)
Allergies: None

Medications:
Medication Name: Lisinopril (for hypertension)
Dosage: 10 mg daily
Frequency: Daily
Medication Name: Albuterol (for asthma)
Dosage: As needed
Frequency: As needed
Medication Name: Advair (for asthma)
Dosage: As prescribed
Frequency: As prescribed

Hospitalizations:
Hospital Name: Green Hills General Hospital
Reason: Appendectomy
Date: March 20, 1992

Surgeries:

Surgery Type: Appendectomy
Date: March 20, 1992 ->:
"""]

sequences = pipeline(
    test_data,
    max_length=1024,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")

0 0 Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Michelle Anderson
Date of Birth: June 5, 1970
Gender: Female
Address: 123 Oakwood Drive, Green Hills, CA
Phone Number: (555) 123-4567
Email: michelle.anderson@email.com
Occupation: Registered Nurse

Dependents:
Spouse:
Full Name: David Anderson
Date of Birth: August 15, 1968
Gender: Male
Relationship: Husband
Dependent Type: Adult

Child:
Full Name: Emily Anderson
Date of Birth: November 20, 1995
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Rachel Smith
Last Medical Checkup Date: August 5, 2023
Medical Conditions:
Hypertension
Diagnosis Date: January 5, 2010
Treatment: Medication (Lisinopril)
Asthma
Diagnosis Date: August 15, 2000
Treatment: Inhalers (Albuterol and Advair)
Allergies: None

Medications:
Medication Name: Lisinopril (for hypertension)
Dosage: 10 mg daily
Frequency: Daily
Medication Name: Albuterol (for asthma)
Dosage: As needed
Frequency: As needed
Medication Name: Advair (for asthma)
Dosage: As prescribed
Frequency: As prescribed

Hospitalizations:
Hospital Name: Green Hills General Hospital
Reason: Appendectomy
Date: March 20, 1992

Surgeries:

Surgery Type: Appendectomy
Date: March 20, 1992 ->:
Hospital Name: Green Hills General Hospital
Surgeon Name: Dr. Michael Smith

 ->:
Policy Details:
Premium Amount: $500/month
Coverage Duration: 12 months per calendar year
Deductible Amount: $1,000/individual, $2,000/family
Co-Pay Amount: $30 for non-prescription medications, $50 for prescription medications
Out-of-Pocket Maximum: $5,000/individual, $10,000/family
Prescription Coverage: Included in this policy

Additional Coverage:

1. Mental Health & Mental Illness:
    - Coverage for a range of mental health services, including therapy and medication.
2. Dental Coverage:
    - Included in this policy, coverage for routine cleanings, examinations, and preventive treatments.
3. Vision Coverage:
    - Included in this policy, coverage for glasses and contact lenses.
4. Maternity Coverage:
    - Included in this policy, coverage for obstetrician consultations, delivery procedures, and pre- and postnatal care.
5. Emergency Coverage:
    - Included in this policy, emergency room visits, ambulance transports, and emergency hospitalizations are covered, subject to applicable co-pays or deductibles.
6. Prescription Coverage:
    - Included in this policy, coverage for a range of prescription medications, subject to co-payments or deductibles.
7. Preventive Coverage:
    - Included in this policy, coverage for preventive healthcare services, including vaccines, screenings, and wellness visits.
8. Specialty Coverage:
    - Included in this policy, coverage for specialized healthcare services such as physical therapy, diagnostic tests, and hospitalization for chronic conditions.
9. Health & Wellness:
    - Included in this policy, coverage for health and wellness programs, such as gym memberships, weight management programs, and smoking cessation programs.

Policy Details Regarding Coverage for Dependents:

- Dependent coverage is subject to the same terms and conditions as primary coverage, with the following differences

In [ ]:
## AFTER FINETUNING
test_data = ["""Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Robert Johnson
Date of Birth: September 5, 1976
Gender: Male
Address: 789 Maple Lane, Riverside, NY
Phone Number: (555) 987-6543
Email: robert.johnson@email.com
Occupation: Accountant

Dependents:

1. Full Name: Olivia Johnson
Date of Birth: December 3, 2005
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Michael Davis
Last Medical Checkup Date: August 12, 2023
Medical Conditions: High Blood Pressure
Allergies: None
Medications:
Medication Name: Lisinopril
Dosage: 10 mg daily
Frequency: Daily
Hospitalizations:

Hospital Name: Riverside General Hospital
Reason: Kidney Stone
Date: July 15, 2010
Surgeries:

Surgery Type: Appendectomy ->:
"""]

sequences = pipeline(
    test_data,
    max_length=1024,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

0 Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Robert Johnson
Date of Birth: September 5, 1976
Gender: Male
Address: 789 Maple Lane, Riverside, NY
Phone Number: (555) 987-6543
Email: robert.johnson@email.com
Occupation: Accountant

Dependents:

1. Full Name: Olivia Johnson
Date of Birth: December 3, 2005
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Michael Davis
Last Medical Checkup Date: August 12, 2023
Medical Conditions: High Blood Pressure
Allergies: None
Medications:
Medication Name: Lisinopril
Dosage: 10 mg daily
Frequency: Daily
Hospitalizations:

Hospital Name: Riverside General Hospital
Reason: Kidney Stone
Date: July 15, 2010
Surgeries:

Surgery Type: Appendectomy ->:
Date: March 5, 1997
Hospital: Riverside General Hospital
Surgeon: Dr. Robert Jones

Surgery Type: Carpal Tunnel Surgery ->:
Date: January 15, 2020
Hospital: Riverside General Hospital
Surgeon: Dr. Mary Johnson

2. Full Name: Emily Johnson
Date of Birth: January 1, 2013
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Sarah Davis
Last Medical Checkup Date: June 20, 2022
Medical Conditions: Asthma, Eczema, and Mild Anxiety
Medications:
Medication Name: Albuterol
Dosage: 2 puffs every 4 hours as needed
Frequency: As needed
Allergies:
- Penicillin: Severe Allergy
- Codeine: Allergy unknown
- Sulfa: Allergy unknown
- Dexamethasone: Allergy unknown

3. Full Name: Sarah Jones
Date of Birth: August 15, 1993
Gender: Female
Relationship: Daughter-in-law
Dependent Type: Spouse

Medical History:
Primary Care Physician: Dr. Sarah Davis
Last Medical Checkup Date: June 20, 2022
Medical Conditions: No known medical conditions
Allergies: Penicillin, Codeine, Sulfa, and Dexamethasone
Medications:
Medication Name: Multivitamin
Dosage: One tablet daily
Frequency: Daily

4. Full Name: Michael Jones
Date of Birth: March 25, 1969
Gender: Male
Relationship: Son-in-law
Dependent Type: Spouse

Medical History:
Last Medical Checkup Date: March 12, 2023
Medical Conditions: High Cholesterol
Allergies: Penicillin

5. Full Name: Emily Jones
Date of Birth: September 1, 2003
Gender: Female
Relationship: Child
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Sarah Davis
Last Medical Checkup Date: May 12, 2023
Medical Conditions: No known medical conditions
Allergies: None
Medications:
Medication Name: Multivitamin
Dosage: One tablet daily
Frequency: Daily

Policy Details:

Premium Payment Amount: $300 per month
Deductible: $1,000
Co-pay (In Network):
- Primary Care Physician: $20
- Specialist: $40
- Prescription Medication:
    - Generic: $10
    - Brand Name: $50
- Emergency Room Visit: $150
- Urgent Care Visit: $75
- Hospitalization:
    -

In [ ]:
## AFTER FINETUNING
test_data = ["""Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Amisha Dixit
Date of Birth: October 13, 1994
Gender: Female
Address: 1b003, Suncity Gloria, Bangalore, India
Phone Number: (91) 1289024802
Email: amishadixit2738@email.com

Dependents:
1. Full Name: Aarav Dixit
Date of Birth: November 12, 2017
Gender: Male
Relationship: Son
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Jassi Madhav
Last Medical Checkup Date: July 25, 2023
Medical Conditions: None
Allergies: None

Medications:
Medication Name: None
Dosage: N/A
Frequency: N/A

Hospitalizations:
Hospital Name: Lakshmi Medical Center
Reason: None
Date: N/A
Surgeries:

Surgery Type: None ->:
"""]

sequences = pipeline(
    test_data,
    max_length=800,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

/usr/local/lib/python3.10/dist-packages/transformers/pipelines/base.py:1101: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(

0 Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Amisha Dixit
Date of Birth: October 13, 1994
Gender: Female
Address: 1b003, Suncity Gloria, Bangalore, India
Phone Number: (91) 1289024802
Email: amishadixit2738@email.com

Dependents:
1. Full Name: Aarav Dixit
Date of Birth: November 12, 2017
Gender: Male
Relationship: Son
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Jassi Madhav
Last Medical Checkup Date: July 25, 2023
Medical Conditions: None
Allergies: None

Medications:
Medication Name: None
Dosage: N/A
Frequency: N/A

Hospitalizations:
Hospital Name: Lakshmi Medical Center
Reason: None
Date: N/A
Surgeries:

Surgery Type: None ->:
Date: N/A
Reason: None

Insurance Policy Details:

Type of Policy: Comprehensive Health Insurance
Plan Level: Gold

Policy Details:
- Premium Amount: $300 per month
- Deductible Amount: $1,000
- Co-payment Amount: $40 for Primary Care Physician Visits
- Out-of-Pocket Maximum: $5,000
- Prescription Drug Coverage: Included

Policy Extensions:
- Maternity Coverage: Included
- Dental Care Coverage: Additional Coverage Required (not included in policy)
- Vision Care Coverage: Additional Coverage Required (not included in policy)
- Mental Health Coverage: Included

Policy Exclusions:
- Elective Surgery
- Cosmetic Procedures
- Expensive Medical Equipment
- Illegal Drugs (unless in an emergency situation)

Policy Details
- Pre-Authorization and Referrals Requirements: Pre-authorization for specialized services or medical procedures, including surgeries, may be required before the service is rendered.
- Out-of-Network Coverage: Coverage for certain services may be limited when outside of the policy network, and the policy holder may be responsible for any additional charges.
- Emergency Coverage: Emergency medical treatment outside of the policy coverage network are generally covered.

Expiration Date: December 31, 2023
Renewal Details: The policy will automatically renew each year upon receipt of premium payment by the policyholder.

Termination Details:
- Termination of policy coverage can be initiated by either the policyholder or the insurance company.
- The policy holder needs to provide 30 days' notice before the termination date, and any premiums paid in advance will be refunded.
- Any medical expenses incurred during the termination period may not be covered, and policy coverage is terminated upon payment of any outstanding premiums or out-of-pocket medical expenses incurred during the termination period.
- Upon termination of policy coverage, any accumulated cash benefits (if applicable) will be paid out to the policyholder.

In [ ]:
## AFTER FINETUNING
test_data = ["""Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Lisa Johnson
Date of Birth: July 12, 1972
Gender: Female
Address: 789 Elm Street, Harborview, CA
Phone Number: (555) 987-6543
Email: lisa.johnson@email.com
Occupation: Marketing Manager

Dependents:

1.Full Name: Jack Johnson
Date of Birth: May 20, 2009
Gender: Male
Relationship: Son
Dependent Type: Child

2. Full Name: Jasmine Johnson
Date of Birth: May 20, 2009
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Sarah Lewis
Last Medical Checkup Date: August 28, 2023

Medical Conditions: None

Allergies: None

Medications:

Medication Name: None
Dosage: N/A
Frequency: N/A
Hospitalizations:

Hospital Name: Harborview Medical Center
Reason: None
Date: N/A
Surgeries:

Surgery Type: None ->:
"""]

sequences = pipeline(
    test_data,
    max_length=800,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

0 Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Lisa Johnson
Date of Birth: July 12, 1972
Gender: Female
Address: 789 Elm Street, Harborview, CA
Phone Number: (555) 987-6543
Email: lisa.johnson@email.com
Occupation: Marketing Manager

Dependents:

1.Full Name: Jack Johnson
Date of Birth: May 20, 2009
Gender: Male
Relationship: Son
Dependent Type: Child

2. Full Name: Jasmine Johnson
Date of Birth: May 20, 2009
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Sarah Lewis
Last Medical Checkup Date: August 28, 2023

Medical Conditions: None

Allergies: None

Medications:

Medication Name: None
Dosage: N/A
Frequency: N/A
Hospitalizations:

Hospital Name: Harborview Medical Center
Reason: None
Date: N/A
Surgeries:

Surgery Type: None ->:
Reason:
Date: N/A

 ->:

- Policy Details:
Annual Premium: $4,000
Deductible: $1,500
Co-pay: $30 for primary care doctor visits, $40 for specialist visits
Out-of-Pocket Maximum: $5,000
Prescription Coverage: Generic medications covered at a co-pay of $10, while branded medications have a co-pay of $30.
Maternity Coverage: 100% coverage for prenatal visits and labor-related expenses, including delivery and post-natal care.
Mental Health Coverage: 5 sessions per year covered at a co-pay of $40.
Dental Coverage: D

In [ ]:
## AFTER FINETUNING
test_data = ["""Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Michelle Anderson
Date of Birth: June 5, 1970
Gender: Female
Address: 123 Oakwood Drive, Green Hills, CA
Phone Number: (555) 123-4567
Email: michelle.anderson@email.com
Occupation: Registered Nurse

Dependents:
Spouse:
Full Name: David Anderson
Date of Birth: August 15, 1968
Gender: Male
Relationship: Husband
Dependent Type: Adult

Child:
Full Name: Emily Anderson
Date of Birth: November 20, 1995
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Rachel Smith
Last Medical Checkup Date: August 5, 2023
Medical Conditions:
Hypertension
Diagnosis Date: January 5, 2010
Treatment: Medication (Lisinopril)
Asthma
Diagnosis Date: August 15, 2000
Treatment: Inhalers (Albuterol and Advair)
Allergies: None

Medications:
Medication Name: Lisinopril (for hypertension)
Dosage: 10 mg daily
Frequency: Daily
Medication Name: Albuterol (for asthma)
Dosage: As needed
Frequency: As needed
Medication Name: Advair (for asthma)
Dosage: As prescribed
Frequency: As prescribed

Hospitalizations:
Hospital Name: Green Hills General Hospital
Reason: Appendectomy
Date: March 20, 1992

Surgeries:

Surgery Type: Appendectomy
Date: March 20, 1992
->:
"""]

sequences = pipeline(
    test_data,
    max_length=800,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

0 Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Michelle Anderson
Date of Birth: June 5, 1970
Gender: Female
Address: 123 Oakwood Drive, Green Hills, CA
Phone Number: (555) 123-4567
Email: michelle.anderson@email.com
Occupation: Registered Nurse

Dependents:
Spouse:
Full Name: David Anderson
Date of Birth: August 15, 1968
Gender: Male
Relationship: Husband
Dependent Type: Adult

Child:
Full Name: Emily Anderson
Date of Birth: November 20, 1995
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Rachel Smith
Last Medical Checkup Date: August 5, 2023
Medical Conditions:
Hypertension
Diagnosis Date: January 5, 2010
Treatment: Medication (Lisinopril)
Asthma
Diagnosis Date: August 15, 2000
Treatment: Inhalers (Albuterol and Advair)
Allergies: None

Medications:
Medication Name: Lisinopril (for hypertension)
Dosage: 10 mg daily
Frequency: Daily
Medication Name: Albuterol (for asthma)
Dosage: As needed
Frequency: As needed
Medication Name: Advair (for asthma)
Dosage: As prescribed
Frequency: As prescribed

Hospitalizations:
Hospital Name: Green Hills General Hospital
Reason: Appendectomy
Date: March 20, 1992

Surgeries:

Surgery Type: Appendectomy
Date: March 20, 1992
->:

Medical History for Dependents:
- Spouse:
- David Anderson (Hypertension, Diagnosed in 2010)
- Allergies: None

- Emily Anderson (Asthma, Diagnosed at age 5 in 2000)
- Allergies: None


 ->:

In [ ]:
## AFTER FINETUNING
test_data = ["""Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Rishika Thakur
Date of Birth: November 15, 1990
Gender: Female
Address: 154, Sunpharma Road, Vadodara
Phone Number: +91 8473894725
Email: ririthakur3@email.com
Occupation: Doctor

Dependents:
Spouse:
Full Name: Dhruv Thakur
Date of Birth: June 21, 1988
Gender: Male
Relationship: Husband
Dependent Type: Adult

Child:
Full Name: Esha Thakur
Date of Birth: November 12, 2020
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:

Primary Care Physician: Dr. Rakhi Sharma
Last Medical Checkup Date: August 5, 2023
Medical Conditions:
Type 2 Diabetes
Diagnosis Date: June 10, 2015
Treatment: Insulin and Metformin
Arthritis
Diagnosis Date: November 8, 2005
Treatment: Nonsteroidal Anti-Inflammatory Drugs (NSAIDs)
Allergies: None

Medications:
Medication Name: Insulin (for diabetes)
Dosage: As prescribed
Frequency: As prescribed
Medication Name: Metformin (for diabetes)
Dosage: 500 mg twice daily
Frequency: Daily
Medication Name: Ibuprofen (for arthritis)
Dosage: 400 mg as needed
Frequency: As needed
Hospitalizations:

Hospital Name: Green Hills General Hospital
Reason: Knee Replacement Surgery
Date: May 8, 2018
Hospital Name: Green Hills General Hospital
Reason: Gallbladder Removal Surgery
Date: June 15, 2022
Surgeries:

Surgery Type: Knee Replacement Surgery
Date: May 8, 2018
Surgery Type: Gallbladder Removal Surgery
Date: June 15, 2022 ->:
"""]

sequences = pipeline(
    test_data,
    max_length=800,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

0 Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Rishika Thakur
Date of Birth: November 15, 1990
Gender: Female
Address: 154, Sunpharma Road, Vadodara
Phone Number: +91 8473894725
Email: ririthakur3@email.com
Occupation: Doctor

Dependents:
Spouse:
Full Name: Dhruv Thakur
Date of Birth: June 21, 1988
Gender: Male
Relationship: Husband
Dependent Type: Adult

Child:
Full Name: Esha Thakur
Date of Birth: November 12, 2020
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:

Primary Care Physician: Dr. Rakhi Sharma
Last Medical Checkup Date: August 5, 2023
Medical Conditions:
Type 2 Diabetes
Diagnosis Date: June 10, 2015
Treatment: Insulin and Metformin
Arthritis
Diagnosis Date: November 8, 2005
Treatment: Nonsteroidal Anti-Inflammatory Drugs (NSAIDs)
Allergies: None

Medications:
Medication Name: Insulin (for diabetes)
Dosage: As prescribed
Frequency: As prescribed
Medication Name: Metformin (for diabetes)
Dosage: 500 mg twice daily
Frequency: Daily
Medication Name: Ibuprofen (for arthritis)
Dosage: 400 mg as needed
Frequency: As needed
Hospitalizations:

Hospital Name: Green Hills General Hospital
Reason: Knee Replacement Surgery
Date: May 8, 2018
Hospital Name: Green Hills General Hospital
Reason: Gallbladder Removal Surgery
Date: June 15, 2022
Surgeries:

Surgery Type: Knee Replacement Surgery
Date: May 8, 2018
Surgery Type: Gallbladder Removal Surgery
Date: June 15, 2022 ->:

 ->:








Expiration Date: December 31, 2023

Coverage Areas:
The policy covers healthcare expenses incurred within India, both for treatment received within India as well as for medical services received while traveling abroad.

Policy Details:

Deductible:
- The deductible is set at INR 50,000 (Indian Rupees Fifty Thousand), which means that the policy holder should pay for all healthcare expenses up to this deductible amount before the insurance coverage begins.

Coverage Limitations:
- This policy does not cover pre-existing conditions in its basic coverage plan. To cover pre-existing conditions, an additional coverage rider may need to be added to the policy at an extra cost and premiums, as determined by the insurer.
- It does not provide 100% coverage

In [27]:
## AFTER FINETUNING
test_data = ["""Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Kevin Walker
Date of Birth: April 30, 1985
Gender: Male
Address: 456 Maple Street, Riverside, FL
Phone Number: (555) 789-1234
Email: kevin.walker@email.com
Occupation: Electrician

Dependents:
Spouse:
Full Name: Jessica Walker
Date of Birth: September 20, 1987
Gender: Female
Relationship: Wife
Dependent Type: Adult

Medical History:
Primary Care Physician: Dr. Thomas Brown
Last Medical Checkup Date: August 10, 2023
Medical Conditions:
Chronic Back Pain
Diagnosis Date: July 5, 2015
Treatment: Physical Therapy and Pain Medication
Migraine Headaches
Diagnosis Date: April 15, 2007
Treatment: Triptans and Lifestyle Management
Allergies: None

Medications:
Medication Name: Naproxen (for back pain)
Dosage: 500 mg twice daily
Frequency: Daily
Medication Name: Sumatriptan (for migraines)
Dosage: 100 mg as needed
Frequency: As needed

Hospitalizations:
Hospital Name: Riverside Medical Center
Reason: Appendectomy
Date: February 18, 2010

Surgeries:
None ->:
"""]

sequences = pipeline(
    test_data,
    max_length=800,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

0 Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Kevin Walker
Date of Birth: April 30, 1985
Gender: Male
Address: 456 Maple Street, Riverside, FL
Phone Number: (555) 789-1234
Email: kevin.walker@email.com
Occupation: Electrician

Dependents:
Spouse:
Full Name: Jessica Walker
Date of Birth: September 20, 1987
Gender: Female
Relationship: Wife
Dependent Type: Adult

Medical History:
Primary Care Physician: Dr. Thomas Brown
Last Medical Checkup Date: August 10, 2023
Medical Conditions:
Chronic Back Pain
Diagnosis Date: July 5, 2015
Treatment: Physical Therapy and Pain Medication
Migraine Headaches
Diagnosis Date: April 15, 2007
Treatment: Triptans and Lifestyle Management
Allergies: None

Medications:
Medication Name: Naproxen (for back pain)
Dosage: 500 mg twice daily
Frequency: Daily
Medication Name: Sumatriptan (for migraines)
Dosage: 100 mg as needed
Frequency: As needed

Hospitalizations:
Hospital Name: Riverside Medical Center
Reason: Appendectomy
Date: February 18, 2010

Surgeries:
None ->:

Emergency Contact:
1. Name: Jessica Walker
2. Relationship: Wife
3. Contact Information: (555) 789-1231 (Cell)

Medical Insurance:
Policy Holder Policy Number: P23456
Spouse Policy Number: S23457

Policy Details:
Coverage Amount: $500,000
Deductible: $1,500
Co-Pay: $30 for primary care and specialist visits and $50 for emergency room visits
Prescription Coverage:
Generic: $15 for 30-day supply
Brand-Name: $50 for 30-day supply (with prior authorization)
Specialty Medication: $150 for 30-day supply
Vaccines: Covered 100%
Preventive Care: 100% coverage with no deductible or co-payment

Policy Coverage Areas:
1. United States:
 - Coverage for emergency care and medical services when traveling abroad is limited to the plan deductible amount.

2. Emergency Coverage:
- Covered for medical emergencies that occur when you are outside the United States:

a. Emergency Room Visit: 100% coverage of emergency room visits when outside the United States, up to the deductible amount.

b. Urgent Care: Up to the deductible amount, but no coverage for follow-up appointments.

c. Hospitalization: 100% coverage, up to the coverage limit.

d. Prescription Medications: 100% coverage, up to the policy

In [29]:
## AFTER FINETUNING
test_data = ["""
Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Lisa Martinez
Date of Birth: October 12, 1982
Gender: Female
Address: 789 Cedar Avenue, Oakville, NY
Phone Number: (555) 123-4567
Email: lisa.martinez@email.com
Occupation: Pediatrician

Dependents:
Spouse:
Full Name: Carlos Martinez
Date of Birth: December 5, 1980
Gender: Male
Relationship: Husband
Dependent Type: Adult

Child:
Name: Ashley Martinez
Date of Birth: August 23 2010
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Jennifer Adams
Last Medical Checkup Date: September 5, 2023
Medical Conditions:
Asthma
Diagnosis Date: January 10, 1990
Treatment: Inhalers (Albuterol and Advair)
Allergic Rhinitis (Hay Fever)
Diagnosis Date: April 15, 2005
Treatment: Antihistamines
Allergies:
Allergy: Penicillin
Severity: Moderate

Medications:
Medication Name: Albuterol (for asthma)
Dosage: As needed
Frequency: As needed
Medication Name: Advair (for asthma)
Dosage: As prescribed
Frequency: As prescribed
Medication Name: Loratadine (for allergies)
Dosage: 10 mg daily
Frequency: Daily

Hospitalizations:
Hospital Name: Oakville General Hospital
Reason: Kidney Stone
Date: N/A

Surgeries:
Surgery Type: Kidney Stone Removal
Date of Admission: January 19 2007 ->:
"""]

sequences = pipeline(
    test_data,
    max_length=800,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

0
Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Lisa Martinez
Date of Birth: October 12, 1982
Gender: Female
Address: 789 Cedar Avenue, Oakville, NY
Phone Number: (555) 123-4567
Email: lisa.martinez@email.com
Occupation: Pediatrician

Dependents:
Spouse:
Full Name: Carlos Martinez
Date of Birth: December 5, 1980
Gender: Male
Relationship: Husband
Dependent Type: Adult

Child:
Name: Ashley Martinez
Date of Birth: August 23 2010
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Jennifer Adams
Last Medical Checkup Date: September 5, 2023
Medical Conditions:
Asthma
Diagnosis Date: January 10, 1990
Treatment: Inhalers (Albuterol and Advair)
Allergic Rhinitis (Hay Fever)
Diagnosis Date: April 15, 2005
Treatment: Antihistamines
Allergies:
Allergy: Penicillin
Severity: Moderate

Medications:
Medication Name: Albuterol (for asthma)
Dosage: As needed
Frequency: As needed
Medication Name: Advair (for asthma)
Dosage: As prescribed
Frequency: As prescribed
Medication Name: Loratadine (for allergies)
Dosage: 10 mg daily
Frequency: Daily

Hospitalizations:
Hospital Name: Oakville General Hospital
Reason: Kidney Stone
Date: N/A

Surgeries:
Surgery Type: Kidney Stone Removal
Date of Admission: January 19 2007 ->:
Date of Operation: March 8, 2007
Date of Discharge: March 10, 2007

Pre-Existing Conditions:
- Asthma
- Allergic Rhinitis (Hay Fever)
- Kidney Stone
- Diabetes (Type II)
- High Blood Pressure

Diagnosis Date: March 1, 2015
Treatment: As prescribed
Medication: Insulin
Dosage: 1 U per injection, taken before each meal

High Blood Pressure Diagnosis Date: July 2019
Treatment: Blood pressure medication as prescribed
Medication: Amlodipine
Dosage: 5 mg, taken at bedtime.

Policy Details:
Policy Type: Family Health Insurance
Policy Duration: 12 Months
Policy Termination: Cancellation or non-renewal after policy expiration date
Premium Amount: $600 per month
Premium Payment Method: Automatic Withdrawal from Bank Account

Policy Coverage:
- Preventive Care
- Emergency Room Visits
- Hospitalization
- Physical Exams/

In [33]:
## AFTER FINETUNING
test_data = ["""
Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Daniel Lee
Date of Birth: July 20, 1978
Gender: Male
Address: 321 Elm Street, Pineville, TX
Phone Number: (555) 987-6543
Email: daniel.lee@email.com
Occupation: Architect

Dependents:
Spouse:
Full Name: Laura Lee
Date of Birth: March 10, 1982
Gender: Female
Relationship: Wife
Dependent Type: Adult

Child 1:
Full Name: Ethan Lee
Date of Birth: December 15, 2010
Gender: Male
Relationship: Son
Dependent Type: Child

Child 2:
Full Name: Ema Lee
Date of Birth: April 06, 2007
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Susan Wilson
Last Medical Checkup Date: July 10, 2023
Medical Conditions:
Type 2 Diabetes
Diagnosis Date: May 5, 2012
Treatment: Metformin and Dietary Management
High Cholesterol (Hypercholesterolemia)
Diagnosis Date: October 20, 2018
Treatment: Statins (Atorvastatin)
Allergies: None

Medications:
Medication Name: Metformin (for diabetes)
Dosage: 500 mg twice daily
Frequency: Daily
Medication Name: Atorvastatin (for high cholesterol)
Dosage: 20 mg daily
Frequency: Daily

Hospitalizations:
Hospital Name: Pineville Medical Center
Reason: Fever
Date: N/A

Surgeries:
Surgery Type: None ->:
"""]

sequences = pipeline(
    test_data,
    max_length=1024,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

0
Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Daniel Lee
Date of Birth: July 20, 1978
Gender: Male
Address: 321 Elm Street, Pineville, TX
Phone Number: (555) 987-6543
Email: daniel.lee@email.com
Occupation: Architect

Dependents:
Spouse:
Full Name: Laura Lee
Date of Birth: March 10, 1982
Gender: Female
Relationship: Wife
Dependent Type: Adult

Child 1:
Full Name: Ethan Lee
Date of Birth: December 15, 2010
Gender: Male
Relationship: Son
Dependent Type: Child

Child 2:
Full Name: Ema Lee
Date of Birth: April 06, 2007
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Susan Wilson
Last Medical Checkup Date: July 10, 2023
Medical Conditions:
Type 2 Diabetes
Diagnosis Date: May 5, 2012
Treatment: Metformin and Dietary Management
High Cholesterol (Hypercholesterolemia)
Diagnosis Date: October 20, 2018
Treatment: Statins (Atorvastatin)
Allergies: None

Medications:
Medication Name: Metformin (for diabetes)
Dosage: 500 mg twice daily
Frequency: Daily
Medication Name: Atorvastatin (for high cholesterol)
Dosage: 20 mg daily
Frequency: Daily

Hospitalizations:
Hospital Name: Pineville Medical Center
Reason: Fever
Date: N/A

Surgeries:
Surgery Type: None ->:
Surgery Reason: N/A
Date: N/A

 ->:

 ->:

 ->:

 ->:

 ->:

 ->:

 ->:













 ->:

 ->:


 ->:

 ->:

 ->:
-:

Policy Details:
Premium Amount: $600/Month
Deductible: $1,000
Coinsurance: 70%
Out-of-Pocket Maximum: $3,000/Family

Policy Description:
Coverage for healthcare services and medical expenses
Coverage for preventive care, including vaccines and check-ups
Prescription drug coverage
Maternity and newborn care coverage
Dental and vision coverage
Psychiatry coverage
Policy is effective from January 1, 2023

Policy Details:
Coverage for healthcare services and medical expenses
Coverage for preventive care, including vaccines and check-ups
Prescription drug coverage
Maternity and newborn care coverage
Dental and vision coverage
Psychiatry coverage
Policy is effective from January 1, 2023

Policy Details:
Coverage for healthcare services and medical expenses
Coverage for preventive care, including vaccines and check-ups
Prescription drug coverage
Maternity and newborn care coverage
Dental and vision coverage
Psychiatry coverage
Policy is effective from January 1, 2023


Policy Details:
Coverage for healthcare services and medical expenses
Coverage for preventive care, including vaccines and check-ups
Prescription drug coverage
Maternity and newborn care coverage
Dental and vision coverage
Psychiatry coverage
Policy is effective from January 1, 2023

In [31]:
## AFTER FINETUNING
test_data = ["""
Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Rachel Turner
Date of Birth: November 8, 1990
Gender: Female
Address: 789 Birch Road, Harborview, CA
Phone Number: (555) 123-7890
Email: rachel.turner@email.com
Occupation: Software Developer

Dependents:
Spouse:
Full Name: Matthew Turner
Date of Birth: April 15, 1992
Gender: Male
Relationship: Husband
Dependent Type: Adult


Medical History:
Rachel Turner
Primary Care Physician: Dr. Emily Harris
Last Medical Checkup Date: August 15, 2023
Medical Conditions:
Anxiety Disorder
Diagnosis Date: June 5, 2015
Treatment: Cognitive-Behavioral Therapy and Medication (SSRIs)
Seasonal Affective Disorder (SAD)
Diagnosis Date: December 10, 2012
Treatment: Light Therapy and Lifestyle Management
Allergies: None

Medications:
Medication Name: Sertraline (for anxiety)
Dosage: 50 mg daily
Frequency: Daily

Hospitalizations:
Hospital Name: Harborview General Hospital
Reason: None
Date: N/A

Surgeries:

Surgery Type: None

Matthew Turner
Primary Care Physician: Dr. Emily Harris
Last Medical Checkup Date: August 15, 2023
- No pre-existing medical conditions
- Hospitalized for pneumonia in 2016, fully recovered
- No chronic illnesses or disabilities ->:
"""]

sequences = pipeline(
    test_data,
    max_length=1024,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

0
Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Rachel Turner
Date of Birth: November 8, 1990
Gender: Female
Address: 789 Birch Road, Harborview, CA
Phone Number: (555) 123-7890
Email: rachel.turner@email.com
Occupation: Software Developer

Dependents:
Spouse:
Full Name: Matthew Turner
Date of Birth: April 15, 1992
Gender: Male
Relationship: Husband
Dependent Type: Adult


Medical History:
Rachel Turner
Primary Care Physician: Dr. Emily Harris
Last Medical Checkup Date: August 15, 2023
Medical Conditions:
Anxiety Disorder
Diagnosis Date: June 5, 2015
Treatment: Cognitive-Behavioral Therapy and Medication (SSRIs)
Seasonal Affective Disorder (SAD)
Diagnosis Date: December 10, 2012
Treatment: Light Therapy and Lifestyle Management
Allergies: None

Medications:
Medication Name: Sertraline (for anxiety)
Dosage: 50 mg daily
Frequency: Daily

Hospitalizations:
Hospital Name: Harborview General Hospital
Reason: None
Date: N/A

Surgeries:

Surgery Type: None

Matthew Turner
Primary Care Physician: Dr. Emily Harris
Last Medical Checkup Date: August 15, 2023
- No pre-existing medical conditions
- Hospitalized for pneumonia in 2016, fully recovered
- No chronic illnesses or disabilities ->:

 ->:

 ->:

 ->:


Policy Details:
Policy Duration: 1 year (January 1, 2023 - December 31, 2023)
Premium: $500 per month (for both Rachel and Matthew)
Deductibles:
Medical Expenses: $2,000 per individual, $4,000 per family per year
Prescription Drugs: Covered at 50% after the deductible is met
Specialist Consultations: Covered at 90% after the deductible is met
Preventive Services: Covered at 100%

Network Coverage:
- In-network providers: Covered at 90% after the deductible is met
- Out-of-network providers: Covered at 70%

Policy Details:
Policy Duration: 1 year (January 1, 2023 - December 31, 2023)
Premium: $400 per month (for both Rachel and Matthew)
Deductibles:
Medical Expenses: $1,500 per individual, $3,000 per family per year
Prescription Drugs: Covered at 50% after the deductible is met
Specialist Consultations: Covered at 80% after the deductible is met
Preventive Services: Covered at 100%

Network Coverage:
- In-network providers: Covered at 80% after the deductible is met
- Out-of-network providers: Covered at 50%

Policy Details:
Policy Duration: 1 year (January 1, 2023 - December 31, 2023)
Premium: $500 per month (for both Rachel and Matthew)
Deductibles:
Medical Expenses: $2,000 per individual, $4,000 per family per year
Prescription Drugs: Covered at 50% after the deductible is met
Specialist Consultations: Covered at 70% after the deductible is met
Preventive Services: Covered at 100%

Network Coverage:
- In-network providers: Covered at 90% after the deductible is met
- Out-of-network providers: Covered

In [32]:
## AFTER FINETUNING
test_data = ["""
Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Samuel Harris
Date of Birth: March 25, 1986
Gender: Male
Address: 456 Spruce Street, Woodville, TX
Phone Number: (555) 456-7891
Email: samuel.harris@email.com
Occupation: Accountant

Dependents:
Spouse:
Full Name: Olivia Harris
Date of Birth: October 20, 1988
Gender: Female
Relationship: Wife
Dependent Type: Adult

Child:
Full Name: Phoebe Harris
Date of Birth: December 12, 2012
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Samuel Harris
Primary Care Physician: Dr. Michael Turner
Last Medical Checkup Date: September 20, 2023
Medical Conditions:
Asthma
Diagnosis Date: January 5, 1995
Treatment: Inhalers (Albuterol and Advair)
GERD (Gastroesophageal Reflux Disease)
Diagnosis Date: April 15, 2010
Treatment: Proton Pump Inhibitors (PPIs)
Allergies:
Allergy: Shellfish
Severity: Moderate
Medications 12:

Medication Name: Albuterol (for asthma)
Dosage: As needed
Frequency: As needed
Medication Name: Advair (for asthma)
Dosage: As prescribed
Frequency: As prescribed
Medication Name: Omeprazole (for GERD)
Dosage: 20 mg daily
Frequency: Daily

Hospitalizations:
Hospital Name: Woodville Regional Hospital
Reason: Asthma
Date: February 22, 2015

Surgeries:
Surgery Type: None

Olivia Harris
Primary Care Physician: Dr. Michael Turner
Last Medical Checkup Date: March 18, 2023

Medical Conditions:
Anxiety Disorder
Diagnosis Date: June 5, 2015
Treatment: Cognitive-Behavioral Therapy and Medication (SSRIs)

Medications:
Medication Name: Sertraline (for anxiety)
Dosage: 50 mg daily
Frequency: Daily

Phoebe Harris:
- No major health conditions or surgeries in the past 5 years
- Prescription medications: None ->:
"""]

sequences = pipeline(
    test_data,
    max_length=1024,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

0
Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Samuel Harris
Date of Birth: March 25, 1986
Gender: Male
Address: 456 Spruce Street, Woodville, TX
Phone Number: (555) 456-7891
Email: samuel.harris@email.com
Occupation: Accountant

Dependents:
Spouse:
Full Name: Olivia Harris
Date of Birth: October 20, 1988
Gender: Female
Relationship: Wife
Dependent Type: Adult

Child:
Full Name: Phoebe Harris
Date of Birth: December 12, 2012
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Samuel Harris
Primary Care Physician: Dr. Michael Turner
Last Medical Checkup Date: September 20, 2023
Medical Conditions:
Asthma
Diagnosis Date: January 5, 1995
Treatment: Inhalers (Albuterol and Advair)
GERD (Gastroesophageal Reflux Disease)
Diagnosis Date: April 15, 2010
Treatment: Proton Pump Inhibitors (PPIs)
Allergies:
Allergy: Shellfish
Severity: Moderate
Medications 12:

Medication Name: Albuterol (for asthma)
Dosage: As needed
Frequency: As needed
Medication Name: Advair (for asthma)
Dosage: As prescribed
Frequency: As prescribed
Medication Name: Omeprazole (for GERD)
Dosage: 20 mg daily
Frequency: Daily

Hospitalizations:
Hospital Name: Woodville Regional Hospital
Reason: Asthma
Date: February 22, 2015

Surgeries:
Surgery Type: None

Olivia Harris
Primary Care Physician: Dr. Michael Turner
Last Medical Checkup Date: March 18, 2023

Medical Conditions:
Anxiety Disorder
Diagnosis Date: June 5, 2015
Treatment: Cognitive-Behavioral Therapy and Medication (SSRIs)

Medications:
Medication Name: Sertraline (for anxiety)
Dosage: 50 mg daily
Frequency: Daily

Phoebe Harris:
- No major health conditions or surgeries in the past 5 years
- Prescription medications: None ->:

 ->:
Medication Coverage:
Samuel Harris:
- Inhalers (Albuterol and Advair) - 80 pills per month
- Omeprazole - 30 pills per month
- Other prescriptions as required for his medical conditions

Olivia Harris:
- Cognitive-Behavioral Therapy - 1 session per week
- Sertraline - 50 mg daily

Phoebe Harris:
- None

Policy Details:
1. Premium Payment:
  - Monthly: $250
  - Annual: $3,000
2. Deductible: $1,000
3. Co-payment: $5 per prescription
4. Maximum Out-of-Pocket Expenses: $5,000 per year (combined for all members of the family)
5. Preventive Care Coverage:
  - No co-payment on preventive care procedures
  - Wellness visits and immunizations covered at 100%

6. Coverage Details:
  - Inpatient Hospital Care: Covered in full
  - Outpatient Care: Covered in full for general practitioner visits
  - Specialist Care: Covered in part (usually 80%, and co-payment may apply)
  - Emergency Care: Covered in full
  - Maternity Care: Covered in full, including prenatal visits and delivery

7. Coverage Exclusions:
  -

In [39]:
# TRAINING DATA

test_data = ["""Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:

Name: John Smith
Age: 35
Gender: Male
Occupation: Software Engineer
Contact Information: Address: 123 Main Street, Anytown, USA

Phone: (555) 123-4567
Email: johnsmith@example.com

Dependents:
Spouse: Jane Smith (Age: 32)
Children:
Emily Smith (Age: 7)
Ethan Smith (Age: 4)

Medical History:
John Smith:
- No chronic illnesses or pre-existing conditions.
- Last visited a doctor for a routine check-up 6 months ago.
 Jane Smith:
 - No chronic illnesses or pre-existing conditions.
 - Last visited a doctor for a routine check-up 1 year ago.

 Emily Smith:
 - No chronic illnesses or pre-existing conditions.
 - Last visited a doctor for a routine check-up 3 months ago.
 Ethan Smith:
 - No chronic illnesses or pre-existing conditions.
 - Last visited a doctor for a routine check-up 6 months ago.
 ->:
""",
"""
Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:


Name: John Smith
Date of Birth: 01/15/1980
Gender: Male
Occupation: Software Engineer
Contact Information:
- Address: 123 Main Street, Anytown, USA
- Phone: (555) 123-4567
- Email: johnsmith@email.com

Dependents:
Spouse: Jane Smith
Date of Birth: 04/20/1982
Gender: Female
Occupation: Teacher

Medical History:
John Smith:
- No known allergies
- Past medical conditions: None
- Past surgeries: Appendectomy in 2005
Jane Smith:
- Allergies: Penicillin
- Past medical conditions: Asthma
- Past surgeries: None
->:
"""]

sequences = pipeline(
    test_data,
    max_length=1024,  #200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)

for ix,seq in enumerate(sequences):
    print(ix,seq[0]['generated_text'])

0 Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:

Name: John Smith
Age: 35
Gender: Male
Occupation: Software Engineer
Contact Information: Address: 123 Main Street, Anytown, USA

Phone: (555) 123-4567
Email: johnsmith@example.com

Dependents:
Spouse: Jane Smith (Age: 32)
Children:
Emily Smith (Age: 7)
Ethan Smith (Age: 4)

Medical History:
John Smith:
- No chronic illnesses or pre-existing conditions.
- Last visited a doctor for a routine check-up 6 months ago.
 Jane Smith:
 - No chronic illnesses or pre-existing conditions.
 - Last visited a doctor for a routine check-up 1 year ago.

 Emily Smith:
 - No chronic illnesses or pre-existing conditions.
 - Last visited a doctor for a routine check-up 3 months ago.
 Ethan Smith:
 - No chronic illnesses or pre-existing conditions.
 - Last visited a doctor for a routine check-up 6 months ago.
 ->:

 ->:

Coverage Details:
Premium: $500/month
Deductible: $1,000
Co-Payment: $30 for doctor visits
Prescription Drugs: Coverage included with a co-pay of $10 per prescription
Out-of-pocket Maximum: $5,000

Policy Details:
- Coverage includes hospitalizations, surgeries, and specialist consultations.
- Emergency room visits are subject to a co-pay of $50 to $150.
- Maternity coverage included for Jane Smith and Emily Smith with a $250 co-pay for prenatal care.
- Preventive care is covered at 100%. Dental coverage is not included in this policy.
- Coverage is valid for the Smith family within the United States.

 ->:

Signature: - John Smith
- Date: January 15, 2023
- Witness:
  1. Witness Name:
  2. Witness Signature:
  3. Witness Date:

 ->:


Expiration Date:


Coverage Details:
Premium: $1,000/month
Deductible: $500
Co-Payment: $30 for doctor visits, $10 for prescription drugs

Policy Details:
- Coverage includes hospitalizations, surgeries, and specialist consultations.
- Emergency room visits are subject to a co-pay of $50 to $150.
- Maternity coverage included for Jane Smith and Emily Smith with a $250 co-pay for prenatal care.
- Prescription drugs are covered with a co-pay ranging from $5 to $20.
- Preventive care is covered at 100%. Dental coverage included.
- Coverage is valid for the Smith family within the United States.


Signature: - John Smith
- Date: January 15, 2023
- Witness:
  1. Witness Name:
  2. Witness Signature:
  3. Witness Date:


Expiration Date:


Coverage Details:
Premium: $2,000/month
Deductible: $1,000
Co-Payment: $30 for doctor visits, $10 for prescription drugs

Policy Details:
- Coverage includes hospitalizations, surgeries, and specialist consultations.
- Emergency room visits are subject to a co-pay of $50 to $150.
- Maternity coverage included for Jane Smith and Emily Smith with a $250 co-pay for prenatal care.
- Prescription drugs are covered with a co-pay ranging from $10 to $30.
- Preventive care is covered at 100%. Dental coverage included.
- Coverage is valid for the Smith family within the United States.


Signature: - John Smith
- Date: January 15,
1
Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:


Name: John Smith
Date of Birth: 01/15/1980
Gender: Male
Occupation: Software Engineer
Contact Information:
- Address: 123 Main Street, Anytown, USA
- Phone: (555) 123-4567
- Email: johnsmith@email.com

Dependents:
Spouse: Jane Smith
Date of Birth: 04/20/1982
Gender: Female
Occupation: Teacher

Medical History:
John Smith:
- No known allergies
- Past medical conditions: None
- Past surgeries: Appendectomy in 2005
Jane Smith:
- Allergies: Penicillin
- Past medical conditions: Asthma
- Past surgeries: None
->:

 ->:

 ->:

 ->:

Policy Details:
Premium Amount: $500 per month

Coverage Areas:
- Hospitalization
- Emergency Services
- Doctor visits
- Prescription medication
- Dental services
- Maternity and childbirth expenses

Policy Limits:
- Maximum coverage limit per individual: $500,000
- Maximum coverage per year for hospitalization: $100,000
- Maximum coverage per year for maternity and childbirth expenses: $25,000

Deductibles:
- Individual deductible: $3,000
- Family deductible: $6,000

Co-Payments:
- Emergency room visits: $25 per visit
- Physicians visits: $20 per visit
- Prescriptions: Variable - Covers 80% after the individual's deductible (varies by medication)

Prescription Drug Coverage:
- Tier 1: Generic medication (covered at 80% after the individual deductible)
- Tier 2: Preferred brand-name medication (covered at 70% after individual deductible)
- Tier 3: Non-preferred brand-name medication (covered at 50% after individual deductible)
- Tier 4: Specialty medication (variable coverage after individual deductible, depends on the medication)

Policy Details:
- Coverage is valid within the United States (excluding Alaska and Hawaii)
- Coverage will be valid for 12 months from the date of policy purchase, after which the policy will need to be renewed
- The policy will automatically renew every 12 months, unless the policyholder decides to opt out or cancel the policy
- The policy will not cover pre-existing conditions for the first 6 months, unless specifically noted on the policy documents
- The policy is subject to change or cancellation by the insurance company if necessary, at the insurance company's sole discretion

Policy Details:

Coverage Areas:
- Hospitalization: Covered for medical emergencies that require inpatient hospital care. Coverages include room and board expenses, emergency surgery, intensive care unit, anesthesia, and other necessary medical services, up to the coverage limit per policy.
- Emergency Services: Covered expenses for medical emergencies that occur outside of hospital settings. This includes emergency room visits, ambulance transportation, and emergency medical treatment.
- Doctor Visits: Covered expenses for doctor consultations, office visits, diagnostic tests, lab tests, prescription medications, and other necessary medical appointments.
- Prescription Medications: Covered expenses for prescription medications as prescribed by a doctor. Generic, preferred brand-name, and non-preferred brand-name medications may be covered depending on the policy coverage.
- Maternity and Childbirth: Covered expenses for maternity services, prenatal tests, childbirth care, newborn hospital stays, and postnatal care, up to the specified policy limit.
- Dental Services: Covered expenses for routine dental checkups, cleanings, x-rays, dental fillings, root canals, and emergency dental treatment, up to the specified policy limit.
-

**INFERENCE THE MODEL BY DOWNLOADING IT**

In [34]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, AutoTokenizer

base_model_name="TinyPixel/Llama-2-7B-bf16-sharded"
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
)
base_model = AutoModelForCausalLM.from_pretrained(
    base_model_name,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True
)
tokenizer = AutoTokenizer.from_pretrained(base_model_name, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token

Loading checkpoint shards:   0%|          | 0/14 [00:00<?, ?it/s]

In [ ]:
from peft import PeftModel
model = PeftModel.from_pretrained(base_model, "/content")

RuntimeError: ignored

In [ ]:
eval_prompt = """Act as an Insurance underwriting expert for ABC Health Care and give health insurance underwriting as per applicant's information mentioned below:
Full Name: Michelle Anderson
Date of Birth: June 5, 1970
Gender: Female
Address: 123 Oakwood Drive, Green Hills, CA
Phone Number: (555) 123-4567
Email: michelle.anderson@email.com
Occupation: Registered Nurse

Dependents:
Spouse:
Full Name: David Anderson
Date of Birth: August 15, 1968
Gender: Male
Relationship: Husband
Dependent Type: Adult

Child:
Full Name: Emily Anderson
Date of Birth: November 20, 1995
Gender: Female
Relationship: Daughter
Dependent Type: Child

Medical History:
Primary Care Physician: Dr. Rachel Smith
Last Medical Checkup Date: August 5, 2023
Medical Conditions:
Hypertension
Diagnosis Date: January 5, 2010
Treatment: Medication (Lisinopril)
Asthma
Diagnosis Date: August 15, 2000
Treatment: Inhalers (Albuterol and Advair)
Allergies: None

Medications:
Medication Name: Lisinopril (for hypertension)
Dosage: 10 mg daily
Frequency: Daily
Medication Name: Albuterol (for asthma)
Dosage: As needed
Frequency: As needed
Medication Name: Advair (for asthma)
Dosage: As prescribed
Frequency: As prescribed

Hospitalizations:
Hospital Name: Green Hills General Hospital
Reason: Appendectomy
Date: March 20, 1992

Surgeries:

Surgery Type: Appendectomy
Date: March 20, 1992
->:
"""
model_input = tokenizer(eval_prompt, return_tensors="pt").to("cuda")

model.eval()
with torch.no_grad():
    print(tokenizer.decode(model.generate(**model_input, max_new_tokens=100)[0], skip_special_tokens=True))